In [2]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt
from pathlib import Path
import textwrap
import cga_utils
import math
from typing import Iterable, List, Optional, Tuple
import hdbscan
from sklearn.feature_extraction import DictVectorizer
import cluster_features

## v18

In [17]:
errors = pd.read_csv('res/e38_18.csv').query('exact_match == False')
X_features = cluster_features.prepare_matrix(errors, ["calc_pattern", "code_calc_pattern", "scale", "pred_scale"])
cluster_features.try_hdbscan(X_features)

     0  1   2         3
30  15  1   2  0.165829
32  15  3   4  0.185930
27  10  3   4  0.185930
3    2  4  30  0.190955
0    2  1  43  0.206030
25  10  1   3  0.206030
11   4  2  16  0.226131
16   5  2  16  0.226131
4    2  5  25  0.236181
28  10  4   2  0.246231
33  15  4   2  0.246231
1    2  2  32  0.256281
21   6  2  14  0.276382
2    2  3  31  0.286432
6    3  2  24  0.296482
15   5  1  13  0.296482
9    3  5  18  0.296482
26  10  2   6  0.316583
17   5  3  10  0.316583
10   4  1  18  0.316583
29  10  5   3  0.336683
34  15  5   3  0.336683
14   4  5  15  0.341709
22   6  3   8  0.341709
13   4  4  14  0.341709
8    3  4  14  0.341709
20   6  1  11  0.346734
19   5  5  11  0.356784
24   6  5  11  0.356784
5    3  1  22  0.356784
18   5  4  11  0.371859
23   6  4   9  0.396985
7    3  3  15  0.412060
12   4  3  14  0.427136
31  15  2   3  0.427136

In [18]:
labels, thr = cluster_hdbscan(X_features, min_cluster_size=5, min_samples=2)

NameError: name 'cluster_hdbscan' is not defined

In [127]:
(labels == -1).mean()

0.22613065326633167

In [128]:
labels

array([ 4, 15, 15, -1,  5, 15, 15, -1, -1, 10,  1,  1,  9,  4, 11,  4, -1,
       15, 15,  3,  1, -1, -1, -1, 12, -1, -1, -1, 12, 12,  8, 12, -1, -1,
       13, 13, 13, 14,  5, -1, 13,  5, 14, 10,  0, 10, 13,  6, -1,  9, 12,
       -1,  5,  7, -1,  7, -1, 15, 15,  5, -1,  5, 10, -1, 13, -1, -1, -1,
       15,  9,  9,  6, 14,  8, -1, -1, -1,  2,  6,  6,  6, 11,  4,  1, 14,
        1,  1, 14, 13, 15, -1, -1, -1,  2,  2, 12, -1,  3,  4,  2, -1,  7,
        7,  8,  8, 12, -1,  4, 12, 12,  1,  1, -1, -1,  1,  8, 11, 12, 12,
       -1, 12,  1, -1, -1, 12, 11, 11, 11,  4, 13, 13,  4,  7, 12, 14,  3,
       12,  9,  3,  3,  9, 12, -1, 10,  0,  8, -1,  6, -1, -1,  0, 12,  4,
       10, 15, 15,  5,  6, -1,  8,  6,  8, 15, 10, 12, 12, 13, 15, 15, 12,
       11,  5,  1,  4,  6,  0,  0, -1, 13, -1, 15, 10, 10,  0, -1,  3,  8,
        4, 10,  2, 12,  5, -1,  1, 12, 15, 14, 14, 14])

In [133]:
errors["cluster"] = labels

In [136]:
errors["cluster"].value_counts()

cluster
-1     45
 12    22
 15    17
 1     12
 4     11
 13    11
 10    10
 5      9
 6      9
 8      9
 14     9
 11     7
 0      6
 3      6
 9      6
 7      5
 2      5
Name: count, dtype: int64

In [142]:
#errors[["question","calc_pattern","code_calc_pattern","answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "error_code",  "cluster"]].query('cluster == 12')
errors[["question","calc_pattern","code_calc_pattern","answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "error_code",  "cluster"]].query('cluster == cluster[cluster != -1].value_counts().idxmax()')

,question,calc_pattern,code_calc_pattern,answer,pred,scale,pred_scale,sign_error,x100_flag,error_code,cluster
54,What was the percentage change in Total Other ...,(#-#)/#,((#-#)/#)*#,15.85,15.85,percent,,False,0,scale_error,12
67,What was the percentage change in Adjusted EBI...,(#-#)/#,((#-#)/#)*#,16.36,16.36,percent,,False,0,scale_error,12
68,What was the percentage change in the Total ne...,(#-#)/#,((#-#)/#)*#,-22.26,-22.26,percent,,False,0,scale_error,12
71,What is the percentage increase in the number ...,(#-#)/#,((#-#)/#)*#,58.71,58.71,percent,,False,0,scale_error,12
140,What was the percentage change in net deferred...,(#-#)/#,((#-#)/#)*#,-79.67,NaN,percent,,False,0,runtime_error,12
252,What was the percentage change in the average ...,(#-#)/#,((#-#)/#)*#,-0.57,-0.57,percent,,False,0,scale_error,12
273,What is the percentage change in the total fai...,(#-#)/#,((#-#)/#)*#,0.53,0.53,percent,,False,0,scale_error,12
284,What is the percentage increase in cash provid...,(#-#)/#,((#-#)/#)*#,-21.92,-21.92,percent,,False,0,scale_error,12
285,What is the percentage change in the total oth...,(#-#)/#,((#-#)/#)*#,385.45,385.45,percent,,False,0,scale_error,12
294,What is the percentage change in the research ...,(#-#)/#,((#-#)/#)*#,3.85,3.85,percent,,False,0,scale_error,12
296,What is the percentage change in the finance c...,(#-#)/#,((#-#)/#)*#,222.58,222.58,percent,,False,0,scale_error,12
298,What is the percentage change in cash provided...,(#-#)/#,((#-#)/#)*#,59.99,59.99,percent,,False,0,scale_error,12
303,What is the percentage change of net operating...,(#-#)/#,((#-#)/#)*#,84.53,84.53,percent,,False,0,scale_error,12
326,What was the percentage change in the Share ba...,(#-#)/#,((#-#)/#)*#,6.05,NaN,percent,,False,0,runtime_error,12
336,What was the percentage change in the amount O...,(#-#)/#,((#-#)/#)*#,15.72,15.72,percent,,False,0,scale_error,12
343,What was the percentage change in the number o...,(#-#)/#,((#-#)/#)*#,10.34,10.34,percent,,False,0,scale_error,12
367,What was the percentage change in the amount O...,(#-#)/#,((#-#)/#)*#,-53.55,-53.55,percent,,False,0,scale_error,12
402,What is the percentage change in net income be...,(#-#)/#,((#-#)/#)*#,-13.25,-13.25,percent,,False,0,scale_error,12
409,What is the percentage change in net cash prov...,(#-#)/#,((#-#)/#)*#,33.69,33.69,percent,,False,0,scale_error,12
413,What is the percentage increase in Swiss incom...,(#-#)/#,(#/#)*#,10.15,10.15,percent,,False,0,scale_error,12
475,What is the percentage change of revenue from ...,(#-#)/#,((#-#)/#)*#,23.23,23.23,percent,,False,0,scale_error,12
480,What is the percentage change in the total bal...,(#-#)/#,((#-#)/#)*#,49.92,49.92,percent,,False,0,scale_error,12

In [139]:
errors.to_csv('res/errors_e38_18_cv1_4_2.csv')

## v23

In [24]:
errors = pd.read_csv('res/e38_23.csv').query('exact_match == False')
#X_features = cluster_features.prepare_matrix(errors, ["calc_pattern", "code_calc_pattern", "scale", "pred_scale"])
#X_features = cluster_features.prepare_matrix(errors, ["scale", "pred_scale","x100_flag", "sign_error", 'error_code'])
X_features = cluster_features.prepare_matrix(errors, ["calc_pattern", "code_calc_pattern"])
cluster_features.try_hdbscan(X_features)

     0  1   2         3
30  15  1   4  0.130682
1    2  2  20  0.147727
0    2  1  22  0.159091
2    2  3  20  0.164773
13   4  4  12  0.170455
6    3  2  17  0.181818
20   6  1   9  0.181818
11   4  2  15  0.181818
33  15  4   4  0.187500
22   6  3  10  0.198864
32  15  3   4  0.204545
5    3  1  17  0.204545
4    2  5  18  0.210227
23   6  4   9  0.215909
18   5  4  10  0.215909
17   5  3  12  0.215909
16   5  2  12  0.221591
3    2  4  16  0.221591
12   4  3  14  0.221591
7    3  3  14  0.221591
8    3  4  14  0.221591
25  10  1   6  0.227273
27  10  3   6  0.238636
21   6  2  11  0.250000
10   4  1  14  0.255682
9    3  5  12  0.267045
14   4  5  11  0.284091
15   5  1  12  0.301136
24   6  5  10  0.306818
28  10  4   6  0.306818
19   5  5  10  0.306818
26  10  2   6  0.369318
29  10  5   6  0.397727
34  15  5   4  0.465909
31  15  2   3  0.488636

In [25]:
labels, pers, probs = cluster_features.cluster_hdbscan(X_features, min_cluster_size=4, min_samples=1)
errors["cluster"] = labels
errors["cluster"].value_counts()

pers:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

cluster
-1     45
 10    29
 8     16
 12    14
 6     12
 11    12
 13     7
 5      6
 4      6
 3      6
 9      5
 2      5
 7      5
 1      4
 0      4
Name: count, dtype: int64

# Used in the paper

In [6]:
import numpy as np
from sklearn.preprocessing import StandardScaler
import math

EPS = 1e-9

def value_bucket(ans, pred):
    if ans == pred:
        return 0
    if ans == -1*pred:
        return 1
    if math.isnan(pred):
        return 2
    else: 
        return 3


errors = pd.read_csv('res/e38_31.csv').query('exact_match == False')

# extra features
errors["ratio"] = errors.apply(lambda row: (row["pred"] / (row["answer"]+EPS)) if row["answer"] != 0 else np.inf,  axis=1 )
errors["x100_flag"] = errors["ratio"].apply(lambda ratio: int(0.95 < ratio/100 < 1.05 or 0.95 < ratio*100 < 1.05))

errors["scale"] = errors["scale"].fillna("")
errors["pred_scale"] = errors["pred_scale"].fillna("")
errors["code_calc_pattern"]= errors["code_calc_pattern"].fillna("nan")

errors["scale_mismatch"]= errors["scale"] != errors["pred_scale"]
errors["value_mismatch"]= errors["answer"] != errors["pred"]
errors["value_nan"]= errors["pred"].isna()
errors["value_match"]= errors.apply(lambda row: value_bucket(row["answer"], row["pred"]) ,  axis=1 )

errors["calc_pattern"] = cga_utils.aggregate_calc_patterns(errors["calc_pattern"],3) 
errors["code_calc_pattern"] = cga_utils.aggregate_calc_patterns(errors["code_calc_pattern"],3) 
#convert
#vects = errors[["calc_pattern", "code_calc_pattern", "scale", "pred_scale",'sign_error', "x100_flag"]]
vects = errors[["calc_pattern", "code_calc_pattern", "scale_mismatch", "value_match", "error_code"]]

X_dict = vects.to_dict(orient="records")
dv = DictVectorizer(sparse=False)

X_features = dv.fit_transform(X_dict)#.astype(int)

setups = cluster_features.try_hdbscan(X_features)
print(setups)
#print([ (a,(b,c,d,e)) for (a,b) in setups.iterrows()])
clusterer = hdbscan.HDBSCAN(min_cluster_size=2, min_samples=1, metric="hamming")
clusterer.fit_predict(X_features)

errors["cluster"] = clusterer.labels_

counts = errors["cluster"].value_counts()
print(counts)
errors.to_csv('res/errors_e38_31_cv1_2_1.csv')
for id in counts.index[1:]:    
#errors[["question","calc_pattern","code_calc_pattern","derivation", "answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "error_code",  "cluster"]].query('cluster == cluster[cluster != -1].value_counts().idxmax()')    
    print(id)
    print(errors[["question","calc_pattern","code_calc_pattern","derivation", "answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "error_code",  "cluster"]].query(f'cluster == {id}'))

merging
merging
     0  1   2         3
30  15  1   3  0.100671
25  10  1   4  0.114094
10   4  1  14  0.127517
5    3  1  23  0.127517
20   6  1  12  0.134228
15   5  1  12  0.134228
0    2  1  36  0.154362
32  15  3   2  0.161074
26  10  2   3  0.167785
31  15  2   3  0.167785
33  15  4   2  0.181208
1    2  2  28  0.228188
2    2  3  22  0.248322
4    2  5  26  0.255034
3    2  4  26  0.261745
6    3  2  23  0.268456
21   6  2   7  0.281879
8    3  4  14  0.295302
16   5  2  10  0.295302
27  10  3   3  0.295302
7    3  3  12  0.335570
12   4  3  11  0.335570
11   4  2  14  0.348993
22   6  3   9  0.348993
13   4  4  10  0.355705
17   5  3  10  0.362416
28  10  4   3  0.369128
29  10  5   3  0.369128
34  15  5   3  0.369128
19   5  5  10  0.375839
23   6  4   8  0.382550
18   5  4   9  0.382550
9    3  5  15  0.389262
14   4  5  11  0.409396
24   6  5   7  0.409396
cluster
-1     20
 29    12
 36     7
 2      7
 7      7
 14     5
 22     5
 11     4
 32     4
 3      4
 17     4
 33     4
 15     3
 5      3
 20     3
 0      3
 24     3
 23     3
 8      3
 27     3
 34     3
 1      3
 19     3
 10     3
 12     3
 26     3
 21     2
 4      2
 9      2
 18     2
 30     2
 16     2
 25     2
 6      2
 28     2
 31     2
 13     2
 35     2
Name: count, dtype: int64
29
                                              question calc_pattern  \
170  What is the change in "impact of exchange rate...       #-(-#)
175  What is the change in current ratio from 2018 ...        other
203  What is the difference between the high and lo...          #-#
260  What is the change in Cost of revenue of Softw...          #-#
261  What is the change in Cost of revenue of Clien...          #-#
266  What is the difference of ground leases expiri...          #-#
291  What is the global increase / (decrease) in th...          #-#
293  What is the global increase / (decrease) in th...          #-#
325  What was the change in Impairment losses betwe...          #-#
370  What is the increase / (decrease) in the Weigh...          #-#
387  What is the increase / (decrease) in the prima...          #-#
441  What is the increase / (decrease) in the Opera...          #-#

    code_calc_pattern                         derivation     answer  \
170               #-#                        7.6-(-2.3)        9.90
175               #-#  (121,041/154,619)-(73,202/90,392)      -0.03
203               #-#                   $91.30 - $70.77       20.53
260               #-#                        2,322-2,918    -596.00
261               #-#                            830-261     569.00
266               #-#                         381 - 198      183.00
291               #-#                             7 - 10      -3.00
293               #-#                              1 - 3      -2.00
325               #-#                     200,657-50,565  150092.00
370               #-#                        44.8 - 44.3       0.50
387               nan                    16,981 - 20,251   -3270.00
441               #-#                        1,116 - 723     393.00

          pred     scale pred_scale  sign_error  x100_flag       error_code  \
170       4.66   percent                  False          0  selection_error
175      -0.01              percent       False          0  selection_error
203      17.96                            False          0  selection_error
260       0.00  thousand   thousand       False          0  selection_error
261       0.00  thousand   thousand       False          0  selection_error
266     388.00                            False          0  selection_error
291      -2.00                            False          0  selection_error
293      -1.00                            False          0  selection_error
325       0.00  thousand                  False          0  selection_error
370       0.00   million    million       False          0  selection_error
387  881195.00                            False          0  selection_error
441       0.00   million    million       False          0  selection_error

     cluster
170       29
175       29
203       29
260       29
261       29
266       29
291       29
293       29
325       29
370       29
387       29
441       29
36
                                              question calc_pattern  \
15            What is the 2018 average free cash flow?      (#+#)/#
39   What is the average total current tax expense ...      (#+#)/#
197  What is the average total basic earnings per s...      (#+#)/#
232  What is the average total asset value for 2018...      (#+#)/#
340  What is the 2019 average total amount falling ...      (#+#)/#
341  What is the 2019 average total amount falling ...      (#+#)/#
373  What is the company's average goodwill impairm...      (#+#)/#

    code_calc_pattern           derivation    answer       pred     scale  \
15            (#+#)/#      (4,044+3,316)/2    3680.0    4227.50   million
39            (#+#)/#        (1,018+950)/2     984.0       0.00   million
197           (#+#)/#   (206.2 + 132.6)/2      169.4     338.80
232           (#+#)/#  (5,765.2+5,050.2)/2    5407.7    4474.45   million
340           (#+#)/#  (243,424+221,233)/2  232328.5  470576.00   million
341           (#+#)/#      (3,439+2,480)/2    2959.5    5919.00   million
373           (#+#)/#  (14,740 + 1,910)/2     8325.0    8340.00  thousand

    pred_scale  sign_error  x100_flag       error_code  cluster
15     million       False          0  selection_error       36
39     million       False          0  selection_error       36
197                  False          0  selection_error       36
232    million       False          0  selection_error       36
340    million       False          0  selection_error       36
341    million       False          0  selection_error       36
373   thousand       False          0  selection_error       36
2
                                              question calc_pattern  \
11   What is the proportion of IMFT’s property, pla...          #/#
173                 What is the current ratio in 2019?          #/#
224  What was the domestic-state tax credit carryfo...          #/#
331  What proportion of Total FairValue is made up ...          #/#
412  What is the ratio of the gross cost of land, p...          #/#
436  What is the ratio of inventory reserves to acc...          #/#
484  What is the proportion of long-term debt payme...      (#+#)/#

    code_calc_pattern                   derivation  answer  pred    scale  \
11                #/#                 2,641/3,025     0.87  0.87
173               #/#           121,041 / 154,619     0.78  0.78
224               #/#               $3,313/$39,784    0.08  0.08  percent
331               #/#              442,262/442,262    1.00  1.00
412               #/#                 8,109/8,381     0.97  0.97
436               #/#                     948/358     2.65  2.65
484               #/#  (2,747.6+2,287.0)/10,556.6     0.48  0.48

    pred_scale  sign_error  x100_flag   error_code  cluster
11     percent       False          0  scale_error        2
173   thousand       False          0  scale_error        2
224   thousand       False          0  scale_error        2
331    percent       False          0  scale_error        2
412   thousand       False          0  scale_error        2
436   thousand       False          0  scale_error        2
484    million       False          0  scale_error        2
7
                                              question         calc_pattern  \
34   What was the change in the preferred stock dis...                 -#-#
41   What is the change in the average total curren...  [(#+#)/#]-[(#+#)/#]
185  What is the change in the Total Gross Margin b...                other
253  How much more cloud and license revenues came ...                  #-#
345  What is the change in Income before Income Tax...                  #-#
401  What is the nominal difference in contributed ...                  #-#
464  What was the change in the basic net income pe...                  #-#

    code_calc_pattern                           derivation    answer  pred  \
34                #-#                             -9.9 - 0     -9.90   NaN
41                #-#  [(1,062+1,018)/2] - [(1,018+950)/2]     56.00   NaN
185               #-#                        (41.2%-40.6%)      0.60   NaN
253               #-#                   (18,030 - 4,848)    13182.00   NaN
345               #-#                          103.6-123.8    -20.20   NaN
401               #-#                       6,055 - 5,828     227.00   NaN
464               #-#                            0.43-1.75     -1.32   NaN

       scale pred_scale  sign_error  x100_flag     error_code  cluster
34   percent                  False          0  runtime_error        7
41   million                  False          0  runtime_error        7
185  percent                  False          0  runtime_error        7
253  million                  False          0  runtime_error        7
345  million                  False          0  runtime_error        7
401  million                  False          0  runtime_error        7
464                           False          0  runtime_error        7
14
                                              question calc_pattern  \
69   What is the difference in the number of rights...          #-#
147  What is the change in Allowance for expected c...          #-#
159  What is the increase/ (decrease) in Voyage exp...          #-#
264  From fiscal year 2020 - 2024, what is the diff...          #-#
355  What is the difference between 181-360 and >36...          #-#

    code_calc_pattern              derivation     answer       pred     scale  \
69                #-#  5,691,731 - 4,465,617   1226114.0 -1226114.0
147               #-#                  135-23      112.0     -112.0  thousand
159               #-#           21,387-28,237    -6850.0     6850.0  thousand
264               #-#              697 - 381       316.0     -316.0
355               #-#               2,447-944     1503.0    -1503.0

    pred_scale  sign_error  x100_flag  error_code  cluster
69                    True          0  sign_error       14
147   thousand        True          0  sign_error       14
159   thousand        True          0  sign_error       14
264                   True          0  sign_error       14
355                   True          0  sign_error       14
22
                                              question calc_pattern  \
77   What is the percentage of capital leases in th...          #/#
97   For 2018, what is the percentage of constituti...          #/#
116  What percentage of the total unrealized gain i...          #/#
198  What is the percentage constitution of continu...          #/#
419  What is the percentage constitution of cash in...          #/#

    code_calc_pattern        derivation  answer     pred    scale pred_scale  \
77            (#/#)*#  50,049/8,031,229    0.62     1.25  percent    percent
97            (#/#)*#      7,845/10,647   73.68    36.84  percent    percent
116           (#/#)*#       416/14,650     2.84    96.48  percent    percent
198           (#/#)*#      113.6/204.9    55.44  1314.26  percent    percent
419           (#/#)*#      1,280/1,366    93.70   261.85  percent    percent

     sign_error  x100_flag       error_code  cluster
77        False          0  selection_error       22
97        False          0  selection_error       22
116       False          0  selection_error       22
198       False          0  selection_error       22
419       False          0  selection_error       22
11
                                              question calc_pattern  \
344  What is the change in Net Sales from Fiscal Ye...          #-#
400  What is the average contributed equity at end ...      (#+#)/#
402  What is the percentage change in net income be...      (#-#)/#
435  What is the proportion, in percentage, of defe...      (#+#)/#

    code_calc_pattern              derivation   answer  pred    scale  \
344                 #           1,000.3-908.3    92.00   NaN  million
400               nan      (5,828 + 6,055)/2   5941.50   NaN  million
402                 #  (53,294-61,431)/61,431   -13.25   NaN  percent
435                 #        (425+33)/38,771      1.18   NaN  percent

    pred_scale  sign_error  x100_flag     error_code  cluster
344                  False          0  runtime_error       11
400                  False          0  runtime_error       11
402                  False          0  runtime_error       11
435                  False          0  runtime_error       11
32
                                              question calc_pattern  \
216  What is the average of Net revenues by geograp...    (#+#+#)/#
292  What is the average global regional films (exc...    (#+#+#)/#
361  What was the average amount of total expected ...    (#+#+#)/#
432                  What is the average Gross profit?    (#+#+#)/#

    code_calc_pattern               derivation   answer     pred    scale  \
216               #/#  (9,556+9,664+8,347) / 3  9189.00  4594.50
292               #/#        (49 + 3 + 12) / 3    21.33    13.33
361               #/#            (160+80+49)/3    96.33   144.50  million
432               #/#  (3,696+3,861+3,272) / 3  3609.67  2168.54  million

    pred_scale  sign_error  x100_flag       error_code  cluster
216                  False          0  selection_error       32
292                  False          0  selection_error       32
361    million       False          0  selection_error       32
432    million       False          0  selection_error       32
3
                                              question calc_pattern  \
211  What is the average voyage revenue in 2018 and...      (#+#)/#
213  What is the average net voyage revenue in 2018...      (#+#)/#
357  What is the average depreciation and amortizat...      (#+#)/#
411  What is the proportion of land and leasehold i...      (#+#)/#

    code_calc_pattern              derivation     answer       pred     scale  \
211           (#+#)/#  (289,016 + 317,220)/2   303118.00  303118.00  thousand
213           (#+#)/#  (124,004 + 175,450)/2   149727.00  149727.00  thousand
357           (#+#)/#         (0.1 + 0.1) / 2       0.10       0.10   million
411           (#+#)/#        (672+798)/8,109        0.18       0.18

    pred_scale  sign_error  x100_flag   error_code  cluster
211                  False          0  scale_error        3
213                  False          0  scale_error        3
357                  False          0  scale_error        3
411   thousand       False          0  scale_error        3
17
                                              question calc_pattern  \
257  What was the absolute percentage change in ris...          #-#
258  What was the absolute percentage change in Exp...          #-#
474  How many percent did the weighted average hedg...          #-#
490  What is the percentage of non-vested shares ve...          #/#

    code_calc_pattern          derivation  answer   pred    scale pred_scale  \
257       ((#-#)/#)*#             2.0-1.2    0.80  66.67  percent    percent
258               nan           27.4-33.5   -6.10 -18.21  percent    percent
474       ((#-#)/#)*#           2.10-1.60    0.50  31.25  percent    percent
490       ((#-#)/#)*#  365,223/1,283,281    28.46 -27.48  percent    percent

     sign_error  x100_flag         error_code  cluster
257       False          0  calculation_error       17
258       False          0  calculation_error       17
474       False          0  calculation_error       17
490       False          0  calculation_error       17
33
                                              question calc_pattern  \
118              What were the total expenses in 2019?          #-#
281  What was the change in the total number of sha...          #-#
399  What is the nominal difference for the number ...          #-#
440  What is the increase / (decrease) in Acquisiti...         -#-#

    code_calc_pattern                      derivation      answer      pred  \
118               #-#                 125,843-42,959      82884.0  86603.00
281               #-#                     3,608-3,380       228.0      0.23
399               #-#  1,313,323,941 - 1,258,690,067   54633874.0    -59.00
440               #-#                        -228 - 0      -228.0      0.00

        scale pred_scale  sign_error  x100_flag         error_code  cluster
118   million    million       False          0  calculation_error       33
281  thousand   thousand       False          0  calculation_error       33
399              million       False          0  calculation_error       33
440   million    million       False          0  calculation_error       33
15
                                              question calc_pattern  \
46   What was the increase / (decrease) in the Stat...          #-#
188  What was the difference in the Weighted-Averag...          #-#
194  What is the increase / (decrease) in the Gross...          #-#

    code_calc_pattern         derivation    answer      pred     scale  \
46                #-#    14,694 - 34,105  -19411.0  -19411.0  thousand
188               #-#            5.0-2.0       3.0       3.0
194               #-#  222,859 - 361,046 -138187.0 -138187.0  thousand

    pred_scale  sign_error  x100_flag   error_code  cluster
46                   False          0  scale_error       15
188    million       False          0  scale_error       15
194                  False          0  scale_error       15
5
                                              question calc_pattern  \
125  What was the average Net cash used in financin...    (#+#+#)/#
348  What was the average losses recognized in othe...    (#+#+#)/#
431                 What is the average Cost of sales?    (#+#+#)/#

    code_calc_pattern               derivation   answer     pred    scale  \
125               #/#    (709 + 707 + 429) / 3   615.00  -615.00  million
348       ((#+#)+#)/#           (64+255+389)/3   236.00  -236.00  million
431       ((#+#)+#)/#  (5,860+5,803+5,075) / 3  5579.33 -5579.33  million

    pred_scale  sign_error  x100_flag  error_code  cluster
125    million        True          0  sign_error        5
348    million        True          0  sign_error        5
431    million        True          0  sign_error        5
20
                                              question calc_pattern  \
17   What was the average difference between EBITDA...        other
322  What is the percentage change in total net sal...        other
455  What is the average financing costs between 20...        other

    code_calc_pattern                                        derivation  \
17            (#+#)/#      ((85,123 - 79,046) + (63,954 - 62,575)) / 2
322           (#+#)/#  ((793.4+934.2)-(843.5+1,054.8))/(843.5+1,054.8)
455           (#+#)/#                           [(-2,088) + (-1,074)]/2

      answer     pred     scale pred_scale  sign_error  x100_flag  \
17   3728.00 -2349.00  thousand   thousand       False          0
322    -8.99    -8.69   percent    percent       False          0
455 -1581.00 -4978.00   million    million       False          0

            error_code  cluster
17   calculation_error       20
322  calculation_error       20
455  calculation_error       20
0
                                              question calc_pattern  \
212  What is the average voyage expenses in 2018 an...      (#+#)/#
302  What was the average interest expense for 2018...      (#+#)/#
385  What is the average Allowance for doubtful acc...      (#+#)/#

    code_calc_pattern              derivation    answer      pred     scale  \
212           (#+#)/#  (165,012 + 141,770)/2   153391.0 -153391.0  thousand
302           (#+#)/#    (17,334 + 6,442) / 2   11888.0  -11888.0  thousand
385           (#+#)/#             (16+15) / 2      15.5     -15.5


In [9]:
len (errors)

199

In [19]:
import numpy as np
from sklearn.preprocessing import StandardScaler
import math

EPS = 1e-9

def value_bucket(ans, pred):
    if ans == pred:
        return 0
    if ans == -1*pred:
        return 1
    if math.isnan(pred):
        return 2
    else: 
        return 3


errors = pd.read_csv('res/e38_18.csv').query('exact_match == False')

# extra features
errors["ratio"] = errors.apply(lambda row: (row["pred"] / (row["answer"]+EPS)) if row["answer"] != 0 else np.inf,  axis=1 )
errors["x100_flag"] = errors["ratio"].apply(lambda ratio: int(0.95 < ratio/100 < 1.05 or 0.95 < ratio*100 < 1.05))

errors["scale"] = errors["scale"].fillna("")
errors["pred_scale"] = errors["pred_scale"].fillna("")
errors["code_calc_pattern"]= errors["code_calc_pattern"].fillna("nan")

errors["scale_mismatch"]= errors["scale"] != errors["pred_scale"]
errors["value_mismatch"]= errors["answer"] != errors["pred"]
errors["value_nan"]= errors["pred"].isna()
errors["value_match"]= errors.apply(lambda row: value_bucket(row["answer"], row["pred"]) ,  axis=1 )

errors["calc_pattern"] = cga_utils.aggregate_calc_patterns(errors["calc_pattern"],3) 
errors["code_calc_pattern"] = cga_utils.aggregate_calc_patterns(errors["code_calc_pattern"],3) 
#convert
#vects = errors[["calc_pattern", "code_calc_pattern", "scale", "pred_scale",'sign_error', "x100_flag"]]
vects = errors[["calc_pattern", "code_calc_pattern", "scale_mismatch", "value_match", "error_code"]]

X_dict = vects.to_dict(orient="records")
dv = DictVectorizer(sparse=False)

X_features = dv.fit_transform(X_dict).astype(int)

setups = cluster_features.try_hdbscan(X_features)
print(setups)
#print([ (a,(b,c,d,e)) for (a,b) in setups.iterrows()])
clusterer = hdbscan.HDBSCAN(min_cluster_size=2, min_samples=1, metric="hamming")
clusterer.fit_predict(X_features)

errors["cluster"] = clusterer.labels_

counts = errors["cluster"].value_counts()
print(counts)
#errors.to_csv('res/errors_e38_31_cv1_2_1.csv')
for id in counts.index[:]:    
#errors[["question","calc_pattern","code_calc_pattern","derivation", "answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "error_code",  "cluster"]].query('cluster == cluster[cluster != -1].value_counts().idxmax()')    
    print(id)
    print(errors[["question","calc_pattern","code_calc_pattern","derivation", "answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "error_code",  "cluster"]].query(f'cluster == {id}'))

merging
merging
     0  1   2         3
32  15  3   4  0.130653
0    2  1  45  0.140704
31  15  2   4  0.140704
26  10  2   5  0.140704
33  15  4   3  0.145729
5    3  1  25  0.165829
28  10  4   6  0.195980
27  10  3   6  0.195980
10   4  1  19  0.206030
30  15  1   4  0.216080
25  10  1   5  0.216080
3    2  4  24  0.221106
15   5  1  14  0.221106
4    2  5  23  0.226131
2    2  3  32  0.251256
1    2  2  27  0.261307
34  15  5   2  0.266332
6    3  2  23  0.266332
20   6  1  10  0.271357
8    3  4  14  0.276382
7    3  3  20  0.291457
11   4  2  17  0.291457
9    3  5  15  0.291457
29  10  5   4  0.311558
23   6  4   8  0.316583
18   5  4   9  0.326633
13   4  4  10  0.336683
22   6  3   7  0.341709
16   5  2  11  0.346734
14   4  5  11  0.351759
12   4  3  14  0.381910
21   6  2   8  0.396985
17   5  3   9  0.402010
24   6  5   8  0.412060
19   5  5   8  0.412060
cluster
 24    34
-1     31
 41     8
 6      7
 9      5
 4      5
 26     5
 14     4
 30     4
 36     4
 22     4
 15     4
 27     4
 33     4
 7      3
 3      3
 10     3
 2      3
 18     3
 20     3
 19     3
 17     3
 12     3
 21     3
 44     3
 35     3
 28     2
 37     2
 32     2
 38     2
 16     2
 40     2
 31     2
 0      2
 13     2
 8      2
 42     2
 23     2
 1      2
 25     2
 39     2
 11     2
 5      2
 43     2
 34     2
 29     2
Name: count, dtype: int64
24
                                              question calc_pattern  \
1    What was the percentage change in the amount f...      (#-#)/#
31   What was the percentage change in Total Other ...      (#-#)/#
54   What was the percentage change in Total Other ...      (#-#)/#
67   What was the percentage change in Adjusted EBI...      (#-#)/#
68   What was the percentage change in the Total ne...      (#-#)/#
71   What is the percentage increase in the number ...      (#-#)/#
86   What is the percentage change in the value of ...      (#-#)/#
87   What is the percentage change in the value of ...      (#-#)/#
88   What is the percentage change in the value of ...      (#-#)/#
113  What was the percentage change in cash and cas...      (#-#)/#
182  What is the percentage change in revenues from...      (#-#)/#
227  What is the percentage change in the amounts o...      (#-#)/#
252  What was the percentage change in the average ...      (#-#)/#
256  What was the percentage change in the Total am...      (#-#)/#
273  What is the percentage change in the total fai...      (#-#)/#
283  What was the percentage change in Net income a...      (#-#)/#
284  What is the percentage increase in cash provid...      (#-#)/#
285  What is the percentage change in the total oth...      (#-#)/#
294  What is the percentage change in the research ...      (#-#)/#
296  What is the percentage change in the finance c...      (#-#)/#
298  What is the percentage change in cash provided...      (#-#)/#
303  What is the percentage change of net operating...      (#-#)/#
315  What was the percentage change in Transportati...      (#-#)/#
320  What is the percentage change in the interim d...      (#-#)/#
324  What is the percentage change in Other for def...      (#-#)/#
336  What was the percentage change in the amount O...      (#-#)/#
343  What was the percentage change in the number o...      (#-#)/#
367  What was the percentage change in the amount O...      (#-#)/#
402  What is the percentage change in net income be...      (#-#)/#
409  What is the percentage change in net cash prov...      (#-#)/#
410  What is the percentage change in the net cost ...      (#-#)/#
434  What is the percentage change in gross deferre...      (#-#)/#
475  What is the percentage change of revenue from ...      (#-#)/#
480  What is the percentage change in the total bal...      (#-#)/#

    code_calc_pattern                           derivation  answer    pred  \
1         ((#-#)/#)*#                        (680-774)/774  -12.14  -12.14
31        ((#-#)/#)*#               ($166.3-$513.3)/$513.3  -67.60  -67.60
54        ((#-#)/#)*#                           (95-82)/82   15.85   15.85
67        ((#-#)/#)*#              (108,307-93,081)/93,081   16.36   16.36
68        ((#-#)/#)*#               (14,158-18,211)/18,211  -22.26  -22.26
71        ((#-#)/#)*#  (10,692,594 - 6,737,076)/6,737,076    58.71   58.71
86        ((#-#)/#)*#                     (222 - 191)/191    16.23   16.23
87        ((#-#)/#)*#               (2,370 - 2,929)/2,929   -19.09  -19.09
88        ((#-#)/#)*#                     (668 - 716)/716    -6.70   -6.70
113       ((#-#)/#)*#                  (9,472-7,554)/7,554   25.39   25.39
182       ((#-#)/#)*#               (68,024-67,314)/67,314    1.05    1.05
227       ((#-#)/#)*#                        (0.1-0.1)/0.1    0.00   -0.00
252       ((#-#)/#)*#                     (86.8-87.3)/87.3   -0.57   -0.57
256       ((#-#)/#)*#                     (44.5-41.0)/41.0    8.54    8.54
273       ((#-#)/#)*#               (3,777 - 3,757)/3,757     0.53    0.53
283       ((#-#)/#)*#         ($1,887.8-$1,236.4)/$1,236.4   52.69   52.69
284       ((#-#)/#)*#             (1,389 - 1,779) / 1,779   -21.92  -21.92
285       ((#-#)/#)*#              (41,846 - 8,620)/8,620   385.45  385.45
294       ((#-#)/#)*#               (18,478-17,793)/17,793    3.85    3.85
296       ((#-#)/#)*#                          (200-62)/62  222.58  222.58
298       ((#-#)/#)*#                 (5,798-3,624)/3,624    59.99   59.99
303       ((#-#)/#)*#              (113,475-61,494)/61,494   84.53   84.53
315       ((#-#)/#)*#                  (4,781-4,707)/4,707    1.57    1.57
320       ((#-#)/#)*#               (14,801-13,099)/13,099   12.99   12.99
324       ((#-#)/#)*#                        (577-553)/553    4.34    4.34
336       ((#-#)/#)*#      (3,104,563-2,682,738)/2,682,738   15.72   15.72
343       ((#-#)/#)*#                (1,001.1-907.3)/907.3   10.34   10.34
367       ((#-#)/#)*#            (320,872-690,791)/690,791  -53.55  -53.55
402       ((#-#)/#)*#               (53,294-61,431)/61,431  -13.25  -13.25
409       ((#-#)/#)*#            ($90,253-$67,510)/$67,510   33.69   33.69
410       ((#-#)/#)*#                 (1,298-1,601)/1,601   -18.93  -18.93
434       ((#-#)/#)*#               (38,771-38,721)/38,721    0.13    0.13
475       ((#-#)/#)*#                 (1,761-1,429)/1,429    23.23   23.23
480       ((#-#)/#)*#           (3,933.5-2,623.7)/2,623.7    49.92   49.92

       scale pred_scale  sign_error  x100_flag   error_code  cluster
1    percent    million       False          0  scale_error       24
31   percent    million       False          0  scale_error       24
54   percent                  False          0  scale_error       24
67   percent                  False          0  scale_error       24
68   percent                  False          0  scale_error       24
71   percent                  False          0  scale_error       24
86   percent   thousand       False          0  scale_error       24
87   percent   thousand       False          0  scale_error       24
88   percent   thousand       False          0  scale_error       24
113  percent   thousand       False          0  scale_error       24
182  percent   thousand       False          0  scale_error       24
227  percent    percent       False          0  scale_error       24
252  percent                  False          0  scale_error       24
256  percent    million       False          0  scale_error       24
273  percent                  False          0  scale_error       24
283  percent    million       False          0  scale_error       24
284  percent                  False          0  scale_error       24
285  percent                  False          0  scale_error       24
294  percent                  False          0  scale_error       24
296  percent                  False          0  scale_error       24
298  percent                  False          0  scale_error       24
303  percent                  False          0  scale_error       24
315  percent    million       False          0  scale_error       24
320  percent   thousand       False          0  scale_error       24
324  percent    million       False          0  scale_error       24
336  percent                  False          0  scale_error       24
343  percent                  False          0  scale_error       24
367  percent                  False          0  scale_error       24
402  percent                  False          0  scale_error       24
409  percent                  False          0  scale_error       24
410  percent   thousand       False          0  scale_error       24
434  percent   thousand       False          0  scale_error       24
475  percent                  False          0  scale_error       24
480  percent                  False          0  scale_error       24
-1
                                              question         calc_pattern  \
7    What is the difference between 2019 average de...  [(#+#)/#]-[(#+#)/#]
16   What is the change between 2018 and 2019 avera...  [(#+#)/#]-[(#+#)/#]
17   What was the average difference between EBITDA...                other
41   What is the change in the average total curren...  [(#+#)/#]-[(#+#)/#]
47    What was the average Tax exempt interest income?           -(#+#+#)/#
80   What is the average annual Operating leases co...            (#+#+#)/#
129  What is the average Non-deductible items for 2...             -(#+#)/#
130  What was the average Adjustment for share-base...             -(#+#)/#
145  What is the net percentage difference in net s...              (#-#)/#
185  What is the change in the Total Gross Margin b...                other
200  What is the increase / (decrease) in the Reali...               #-(-#)
201              What was the average realized losses?           -(#+#+#)/#
202  What is the percentage increase / (decrease) i...                #/#-#
237  What is the difference between the net cash us...                other
238  What is the average discount rate for 2018 and...            (#%+#%)/#
240  What is the average rate of price inflation fo...            (#%+#%)/#
253  How much more cloud and license revenues came ...                  #-#
254  What was the total applications revenues in 20...                  #+#
277  What was the percentage change in the Reductio...                other
297  What is the average age of the executive offic...                other
300  What is the total cash provided by all cash fl...                other
330  What proportion of level 2 inputs is made up o...                  #/#
348  What was the average losses recognized in othe...            (#+#+#)/#
356  What was the percentage increase / (decrease) ...                #/#-#
358  What is the percentage increase / (decrease) i...                other
386  What is the increase/ (decrease) in Trade acco...                  #-#
401  What is the nominal difference in contributed ...                  #-#
433  What is the average Gross margin (as percentag...            (#+#+#)/#
435  What is the proportion, in percentage, of defe...              (#+#)/#
455  What is the average financing costs between 20...                other
462  What was the total non-USD denominated monetar...                  #+#

    code_calc_pattern                                    derivation    answer  \
7                 #-#                   [(166+178)/2] - [(57+44)/2]    121.50
16                #-#          [(4,411+4,044)/2] -[(4,044+3,316)/2]    547.50
17            (#+#)/#  ((85,123 - 79,046) + (63,954 - 62,575)) / 2    3728.00
41                  #           [(1,062+1,018)/2] - [(1,018+950)/2]     56.00
47                #/#                       - (197 + 101 + 206) / 3   -168.00
80                #/#                         (4,143+7,111+3,686)/5   2988.00
129           (#+#)/#                              -(0.9 + 0.1) / 2     -0.50
130               #/#                              -(0.4 + 0.6) / 2     -0.50
145           (#/#)*#              (819,073 - 697,280) / 2,941,324       4.14
185               #-#                                 (41.2%-40.6%)      0.60
200               #-#                                 0 - (-42,271)  42271.00
201                 ?                 -(5,062 + 6,533 + 18,494) / 3 -10029.67
202       ((#-#)/#)*#                           21,240 / 82,668 - 1    -74.31
237               #-#                            (-42,056)-(-9,982) -32074.00
238           (#+#)/#                              (2.9% + 3.8%)/2       3.35
240                 ?                              (2.0% + 2.0%)/2       2.00
253           no_code                            (18,030 - 4,848)    13182.00
254                 #                               11,510 + 11,065  22575.00
277       ((#-#)/#)*#                      (-3,144-(-1,102))/-1,102    185.30
297           no_code         (47 + 51 + 64 + 47 + 54 + 41 + 37)/7      48.71
300             other                  $5,121 +$(-5,946) + $17,592   16767.00
330               #/#                                 2,010/442,262      0.45
348       ((#+#)+#)/#                                (64+255+389)/3    236.00
356               nan                               24.9 / 33.5 - 1    -25.67
358               nan                             -25.0 / -33.6 - 1     -0.26
386                 #                                   1,396-1,292    104.00
401               nan                                6,055 - 5,828     227.00
433       ((#+#)+#)/#                          (38.7+40.0+39.2) / 3     39.30
435           (#/#)*#                              (425+33)/38,771       1.18
455               #/#                       [(-2,088) + (-1,074)]/2  -1581.00
462                 #                                  14,732+5,739  20471.00

         pred     scale pred_scale  sign_error  x100_flag         error_code  \
7      109.00   million    million       False          0    selection_error
16        NaN   million                  False          0      runtime_error
17   -2349.00  thousand   thousand       False          0  calculation_error
41      94.00   million    million       False          0    selection_error
47    -168.00  thousand                  False          0        scale_error
80    3887.40  thousand   thousand       False          0  calculation_error
129       NaN   million                  False          0      runtime_error
130     -0.50   million                  False          0        scale_error
145     36.50   percent    percent       False          0  calculation_error
185     -0.60   percent    percent       False          0  calculation_error
200  42271.00  thousand                  False          0        scale_error
201 -34002.00  thousand                  False          0  calculation_error
202    -74.31   percent                  False          0        scale_error
237  32074.00   million    million        True          0         sign_error
238      3.35   percent                  False          0        scale_error
240      2.00   percent                  False          0        scale_error
253       NaN   million                  False          0      runtime_error
254       NaN   million                  False          0      runtime_error
277    185.30   percent                  False          0        scale_error
297       NaN                            False          0      runtime_error
300  16767.00  thousand                  False          0        scale_error
330      1.00   percent                  False          0    selection_error
348   -236.00   million    million        True          0         sign_error
356     -8.60   percent                  False          0    selection_error
358      8.60   percent                  False          0  calculation_error
386    104.00              percent       False          0        scale_error
401       NaN   million                  False          0      runtime_error
433     39.30   percent    million       False          0        scale_error
435      1.18   percent   thousand       False          0        scale_error
455   -553.11   million    million       False          0  calculation_error
462 -34488.00   million    million       False          0  calculation_error

     cluster
7         -1
16        -1
17        -1
41        -1
47        -1
80        -1
129       -1
130       -1
145       -1
185       -1
200       -1
201       -1
202       -1
237       -1
238       -1
240       -1
253       -1
254       -1
277       -1
297       -1
300       -1
330       -1
348       -1
356       -1
358       -1
386       -1
401       -1
433       -1
435       -1
455       -1
462       -1
41
                                              question calc_pattern  \
126  What was the change in Acquisition and integra...          #-#
199  What is the nominal difference for basic earni...          #-#
260  What is the change in Cost of revenue of Softw...          #-#
261  What is the change in Cost of revenue of Clien...          #-#
325  What was the change in Impairment losses betwe...          #-#
370  What is the increase / (decrease) in the Weigh...          #-#
387  What is the increase / (decrease) in the prima...          #-#
469  How much is the change between 2018 and 2019 c...          #-#

    code_calc_pattern       derivation    answer      pred     scale  \
126               #-#             17-8       9.0     130.0   million
199               #-#   206.2 - 132.6       73.6      -9.1
260               #-#      2,322-2,918    -596.0       0.0  thousand
261               #-#          830-261     569.0       0.0  thousand
325               #-#   200,657-50,565  150092.0       0.0  thousand
370               #-#      44.8 - 44.3       0.5       0.0   million
387               #-#  16,981 - 20,251   -3270.0  881195.0
469               #-#      1,740-4,946   -3206.0       0.0   million

    pred_scale  sign_error  x100_flag       error_code  cluster
126    million       False          0  selection_error       41
199                  False          0  selection_error       41
260   thousand       False          0  selection_error       41
261   thousand       False          0  selection_error       41
325   thousand       False          0  selection_error       41
370    million       False          0  selection_error       41
387                  False          0  selection_error       41
469    million       False          0  selection_error       41
6
                                              question calc_pattern  \
69   What is the difference in the number of rights...          #-#
147  What is the change in Allowance for expected c...          #-#
159  What is the increase/ (decrease) in Voyage exp...          #-#
208  What is the nominal difference for ROFE betwee...          #-#
264  From fiscal year 2020 - 2024, what is the diff...          #-#
266  What is the difference of ground leases expiri...          #-#
353  What is the difference in low and medium count...          #-#

    code_calc_pattern              derivation     answer       pred     scale  \
69                #-#  5,691,731 - 4,465,617   1226114.0 -1226114.0
147               #-#                  135-23      112.0     -112.0  thousand
159               #-#           21,387-28,237    -6850.0     6850.0  thousand
208               #-#            17.1 - 15.2         1.9       -1.9   percent
264               #-#              697 - 381       316.0     -316.0
266               #-#              381 - 198       183.0     -183.0
353               #-#               1,347-891      456.0     -456.0

    pred_scale  sign_error  x100_flag  error_code  cluster
69                    True          0  sign_error        6
147   thousand        True          0  sign_error        6
159   thousand        True          0  sign_error        6
208    percent        True          0  sign_error        6
264                   True          0  sign_error        6
266                   True          0  sign_error        6

In [7]:
errors[["question","calc_pattern","code_calc_pattern","derivation", "answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "error_code",  "cluster"]].query(f'cluster == 29')

,question,calc_pattern,code_calc_pattern,derivation,answer,pred,scale,pred_scale,sign_error,x100_flag,error_code,cluster
170,"What is the change in ""impact of exchange rate...",#-(-#),#-#,7.6-(-2.3),9.90,4.66,percent,,False,0,selection_error,29
175,What is the change in current ratio from 2018 ...,other,#-#,"(121,041/154,619)-(73,202/90,392)",-0.03,-0.01,,percent,False,0,selection_error,29
203,What is the difference between the high and lo...,#-#,#-#,$91.30 - $70.77,20.53,17.96,,,False,0,selection_error,29
260,What is the change in Cost of revenue of Softw...,#-#,#-#,"2,322-2,918",-596.00,0.00,thousand,thousand,False,0,selection_error,29
261,What is the change in Cost of revenue of Clien...,#-#,#-#,830-261,569.00,0.00,thousand,thousand,False,0,selection_error,29
266,What is the difference of ground leases expiri...,#-#,#-#,381 - 198,183.00,388.00,,,False,0,selection_error,29
291,What is the global increase / (decrease) in th...,#-#,#-#,7 - 10,-3.00,-2.00,,,False,0,selection_error,29
293,What is the global increase / (decrease) in th...,#-#,#-#,1 - 3,-2.00,-1.00,,,False,0,selection_error,29
325,What was the change in Impairment losses betwe...,#-#,#-#,"200,657-50,565",150092.00,0.00,thousand,,False,0,selection_error,29
370,What is the increase / (decrease) in the Weigh...,#-#,#-#,44.8 - 44.3,0.50,0.00,million,million,False,0,selection_error,29
387,What is the increase / (decrease) in the prima...,#-#,nan,"16,981 - 20,251",-3270.00,881195.00,,,False,0,selection_error,29
441,What is the increase / (decrease) in the Opera...,#-#,#-#,"1,116 - 723",393.00,0.00,million,million,False,0,selection_error,29

In [213]:
counts.index

Index([-1,  5,  7, 14, 28, 37, 22, 38, 19,  8, 16, 20,  2, 15, 39, 32, 25,  4,
       10, 11, 18, 41, 40, 23, 29, 43, 34, 12, 21, 26, 30,  6, 31,  1,  9, 27,
        3, 24, 33,  0, 17, 13, 42, 36, 35],
      dtype='int64', name='cluster')

In [107]:
errors = pd.read_csv('res/e38_23.csv').query('exact_match == False')

#features
errors["ratio"] = errors.apply(lambda row: (row["pred"] / (row["answer"]+EPS)) if row["answer"] != 0 else np.inf,  axis=1 )
errors["x100_flag"] = errors["ratio"].apply(lambda ratio: int(0.95 < ratio/100 < 1.05 or 0.95 < ratio*100 < 1.05))

errors["scale"] = errors["scale"].fillna("")
errors["pred_scale"] = errors["pred_scale"].fillna("")
errors["code_calc_pattern"]= errors["code_calc_pattern"].fillna("nan")

errors["scale_mismatch"]= errors["scale"] != errors["pred_scale"]
errors["value_mismatch"]= errors["answer"] != errors["pred"]

errors["calc_pattern"] = cga_utils.aggregate_calc_patterns(errors["calc_pattern"],3) 
errors["code_calc_pattern"] = cga_utils.aggregate_calc_patterns(errors["code_calc_pattern"],3) 

#ls

errors["l"] = errors["calc_pattern"] +  "||" + errors["code_calc_pattern"] + "||" + errors["scale_mismatch"].astype(str) + "||" + errors["x100_flag"].astype(str) + "||" + errors["sign_error"].astype(str) 
errors["l"].value_counts()

merging
merging

l
#-#||#-#||True||0||False             11
#-#||#-#||False||0||False             9
#-#||((#-#)/#)*#||True||0||False      8
#-#||((#-#)/#)*#||False||0||False     8
#/#||(#/#)*#||False||0||False         7
                                     ..
#/#||#/#||True||1||False              1
#-#||nan||False||0||False             1
#-(-#)||#-#||True||0||False           1
-(#+#+#)/#||?||True||0||False         1
#-#||(#/#)*#||True||0||False          1
Name: count, Length: 71, dtype: int64

In [114]:
errors[["question","calc_pattern","code_calc_pattern","answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "l"]].query('l == "#-#||((#-#)/#)*#||True||0||False"')

,question,calc_pattern,code_calc_pattern,answer,pred,scale,pred_scale,sign_error,x100_flag,l
100,What was the change in the Equity method inves...,#-#,((#-#)/#)*#,-7.00,-26.92,million,percent,False,0,#-#||((#-#)/#)*#||True||0||False
122,What is the increase / (decrease) in revenue f...,#-#,((#-#)/#)*#,1105.00,12.11,million,percent,False,0,#-#||((#-#)/#)*#||True||0||False
126,What was the change in Acquisition and integra...,#-#,((#-#)/#)*#,9.00,288.89,million,percent,False,0,#-#||((#-#)/#)*#||True||0||False
251,What was the change in the average life expect...,#-#,((#-#)/#)*#,-0.50,-0.57,,percent,False,0,#-#||((#-#)/#)*#||True||0||False
280,What was the change in average price paid per ...,#-#,((#-#)/#)*#,0.76,1.17,,percent,False,0,#-#||((#-#)/#)*#||True||0||False
291,What is the global increase / (decrease) in th...,#-#,((#-#)/#)*#,-3.00,-66.67,,percent,False,0,#-#||((#-#)/#)*#||True||0||False
323,What is the change in total sales from fiscal ...,#-#,((#-#)/#)*#,1600.10,20.16,million,percent,False,0,#-#||((#-#)/#)*#||True||0||False
457,What is the change in Total Fees from 2018 to ...,#-#,((#-#)/#)*#,472663.00,2.71,,percent,False,0,#-#||((#-#)/#)*#||True||0||False

In [73]:
import numpy as np
from sklearn.preprocessing import StandardScaler

EPS = 1e-9

errors = pd.read_csv('res/e38_41.csv').query('exact_match == False')

# extra features
errors["ratio"] = errors.apply(lambda row: (row["pred"] / (row["answer"]+EPS)) if row["answer"] != 0 else np.inf,  axis=1 )
errors["x100_flag"] = errors["ratio"].apply(lambda ratio: int(0.95 < ratio/100 < 1.05 or 0.95 < ratio*100 < 1.05))

errors["scale"] = errors["scale"].fillna("")
errors["pred_scale"] = errors["pred_scale"].fillna("")
errors["code_calc_pattern"]= errors["code_calc_pattern"].fillna("nan")

errors["calc_pattern"] = cga_utils.aggregate_calc_patterns(errors["calc_pattern"],3) 
errors["code_calc_pattern"] = cga_utils.aggregate_calc_patterns(errors["code_calc_pattern"],3) 
#convert
vects = errors[["calc_pattern", "code_calc_pattern", "scale", "pred_scale",'sign_error', "x100_flag"]]
X_dict = vects.to_dict(orient="records")
dv = DictVectorizer(sparse=False)
X_features = dv.fit_transform(X_dict).astype(int)
print(cluster_features.try_hdbscan(X_features))
clusterer = hdbscan.HDBSCAN(min_cluster_size=6, min_samples=1, metric="hamming")
clusterer.fit_predict(X_features)

errors["cluster"] = clusterer.labels_

errors.to_csv('res/errors_e38_23_cv1_5_2.csv')

errors[["question","calc_pattern","code_calc_pattern","answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "cluster"]].query('cluster == cluster[cluster != -1].value_counts().idxmax()')

merging
merging
     0  1   2         3
28  10  4   2  0.037267
27  10  3   2  0.149068
26  10  2   2  0.155280
25  10  1   2  0.173913
20   6  1  11  0.180124
15   5  1  11  0.180124
0    2  1  43  0.204969
17   5  3  11  0.229814
2    2  3  26  0.248447
1    2  2  31  0.260870
22   6  3  10  0.260870
30  15  1   2  0.279503
7    3  3  20  0.279503
10   4  1  16  0.285714
5    3  1  24  0.291925
3    2  4  20  0.298137
8    3  4  14  0.304348
12   4  3  15  0.304348
16   5  2  11  0.304348
6    3  2  23  0.310559
31  15  2   2  0.329193
4    2  5  19  0.329193
21   6  2  10  0.335404
11   4  2  18  0.335404
32  15  3   2  0.354037
23   6  4   8  0.378882
18   5  4   9  0.378882
13   4  4   9  0.378882
9    3  5  14  0.378882
33  15  4   2  0.385093
14   4  5  11  0.385093
24   6  5   9  0.434783
29  10  5   2  0.434783
19   5  5   9  0.434783
34  15  5   2  0.434783

,question,calc_pattern,code_calc_pattern,answer,pred,scale,pred_scale,sign_error,x100_flag,cluster
5,What is the 2019 average defined contribution ...,(#+#)/#,#/#,172.00,166.00,million,million,False,0,3
6,What is the 2019 average defined benefit schemes?,(#+#)/#,#/#,50.50,57.00,million,million,False,0,3
14,What is the 2019 average free cash flow?,(#+#)/#,#,4227.50,4411.00,million,million,False,0,3
15,What is the 2018 average free cash flow?,(#+#)/#,nan,3680.00,4044.00,million,million,False,0,3
39,What is the average total current tax expense ...,(#+#)/#,(#+#)/#,984.00,NaN,million,,False,0,3
40,What is the average total current tax expense ...,(#+#)/#,(#+#)/#,1040.00,NaN,million,,False,0,3
95,What is the average RSUs vested?,(#+#+#)/#,#/#,424.00,257.00,million,million,False,0,3
125,What was the average Net cash used in financin...,(#+#+#)/#,#/#,615.00,-615.00,million,million,True,0,3
129,What is the average Non-deductible items for 2...,-(#+#)/#,(#+#)/#,-0.50,NaN,million,,False,0,3
130,What was the average Adjustment for share-base...,-(#+#)/#,(#+#)/#,-0.50,NaN,million,,False,0,3
157,What is the net total underlying rights and ot...,#+#,#+#,16.40,17.00,million,million,False,0,3
197,What is the average total basic earnings per s...,(#+#)/#,(#+#)/#,169.40,338.80,,,False,0,3
211,What is the average voyage revenue in 2018 and...,(#+#)/#,(#+#)/#,303118.00,303118.00,thousand,,False,0,3
212,What is the average voyage expenses in 2018 an...,(#+#)/#,(#+#)/#,153391.00,-153391.00,thousand,,True,0,3
213,What is the average net voyage revenue in 2018...,(#+#)/#,(#+#)/#,149727.00,149727.00,thousand,,False,0,3
232,What is the average total asset value for 2018...,(#+#)/#,(#+#)/#,5407.70,4474.45,million,million,False,0,3
248,What is the Total net revenue for fiscal 2018 ...,#+#,#,3944.00,2280.00,million,million,False,0,3
302,What was the average interest expense for 2018...,(#+#)/#,(#+#)/#,11888.00,-11888.00,thousand,thousand,True,0,3
334,What is the total carrying amount of Senior No...,other,#,1711.40,421.90,million,million,False,0,3
340,What is the 2019 average total amount falling ...,(#+#)/#,#,232328.50,486848.00,million,million,False,0,3
341,What is the 2019 average total amount falling ...,(#+#)/#,(#+#)/#,2959.50,5919.00,million,million,False,0,3
348,What was the average losses recognized in othe...,(#+#+#)/#,((#+#)+#)/#,236.00,-236.00,million,million,True,0,3
357,What is the average depreciation and amortizat...,(#+#)/#,(#+#)/#,0.10,0.10,million,,False,0,3
361,What was the average amount of total expected ...,(#+#+#)/#,#/#,96.33,64.22,million,million,False,0,3
371,What is the average unvested restricted stock?,(#+#)/#,#/#,0.50,0.77,million,million,False,0,3
379,What is the average Net deferred tax liabiliti...,(#+#)/#,(#+#)/#,68462.50,NaN,thousand,,False,0,3
385,What is the average Allowance for doubtful acc...,(#+#)/#,(#+#)/#,15.50,-15.50,,,True,0,3
400,What is the average contributed equity at end ...,(#+#)/#,(#+#)/#,5941.50,NaN,million,,False,0,3
431,What is the average Cost of sales?,(#+#+#)/#,((#+#)+#)/#,5579.33,-5579.33,million,million,True,0,3
432,What is the average Gross profit?,(#+#+#)/#,#/#,3609.67,2168.54,million,million,False,0,3
455,What is the average financing costs between 20...,other,(#+#)/#,-1581.00,-553.11,million,million,False,0,3
461,What was the total USD denominated monetary as...,#+#,#,28101.00,48784.00,million,million,False,0,3
462,What was the total non-USD denominated monetar...,#+#,#,20471.00,-34488.00,million,million,False,0,3
463,What was the total USD denominated monetary as...,#+#,#,20683.00,50778.00,million,million,False,0,3

In [52]:
set(errors["code_calc_pattern"])

{'#',
 '#*#',
 '#+#',
 '#-#',
 '#/#',
 '(#+#)+#',
 '(#+#)/#',
 '(#-#)/#',
 '(#/#)*#',
 '((#+#)+#)/#',
 '((#-#)/#)*#',
 '?',
 nan,
 'no_code'}

In [26]:
errors[["question","calc_pattern","code_calc_pattern","answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "error_code",  "cluster"]].query('cluster == 10')
#errors[["question","calc_pattern","code_calc_pattern","answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "error_code",  "cluster"]].query('cluster == cluster[cluster != -1].value_counts().idxmax()')

,question,calc_pattern,code_calc_pattern,answer,pred,scale,pred_scale,sign_error,x100_flag,error_code,cluster
27,What was the total expenses for Oracle in 2018?,#-#,#-#,35796.0,26119.00,million,million,False,0,calculation_error,10
30,What is the difference in amount between Defer...,#-#,#-#,14212.0,-14212.00,thousand,,True,0,sign_error,10
46,What was the increase / (decrease) in the Stat...,#-#,#-#,-19411.0,-19411.00,thousand,,False,0,scale_error,10
69,What is the difference in the number of rights...,#-#,#-#,1226114.0,-1226114.00,,,True,0,sign_error,10
118,What were the total expenses in 2019?,#-#,#-#,82884.0,42910.00,million,million,False,0,calculation_error,10
138,What was the change in Inventory between 2018 ...,#-#,#-#,535.0,NaN,thousand,,False,0,runtime_error,10
147,What is the change in Allowance for expected c...,#-#,#-#,112.0,-112.00,thousand,thousand,True,0,sign_error,10
159,What is the increase/ (decrease) in Voyage exp...,#-#,#-#,-6850.0,6850.00,thousand,thousand,True,0,sign_error,10
178,What is the total equity of the acquisation as...,#-#,#-#,445.7,445.70,million,,False,0,scale_error,10
188,What was the difference in the Weighted-Averag...,#-#,#-#,3.0,3.00,,million,False,0,scale_error,10
194,What is the increase / (decrease) in the Gross...,#-#,#-#,-138187.0,-138187.00,thousand,,False,0,scale_error,10
195,What is the COGS for 2019?,#-#,#-#,-168630.0,168630.00,thousand,,True,0,sign_error,10
199,What is the nominal difference for basic earni...,#-#,#-#,73.6,-9.10,,,False,0,selection_error,10
208,What is the nominal difference for ROFE betwee...,#-#,#-#,1.9,-1.90,percent,percent,False,0,calculation_error,10
253,How much more cloud and license revenues came ...,#-#,#-#,13182.0,NaN,million,,False,0,runtime_error,10
260,What is the change in Cost of revenue of Softw...,#-#,#-#,-596.0,0.00,thousand,thousand,False,0,selection_error,10
261,What is the change in Cost of revenue of Clien...,#-#,#-#,569.0,0.00,thousand,thousand,False,0,selection_error,10
264,"From fiscal year 2020 - 2024, what is the diff...",#-#,#-#,316.0,-316.00,,,True,0,sign_error,10
266,What is the difference of ground leases expiri...,#-#,#-#,183.0,-183.00,,,True,0,sign_error,10
325,What was the change in Impairment losses betwe...,#-#,#-#,150092.0,0.00,thousand,,False,0,selection_error,10
338,What was the change in Net operating loss carr...,#-#,#-#,590.0,NaN,thousand,,False,0,runtime_error,10
342,What was the change in the number of shares gr...,#-#,#-#,93.8,93.80,thousand,,False,0,scale_error,10
345,What is the change in Income before Income Tax...,#-#,#-#,-20.2,NaN,million,,False,0,runtime_error,10
355,What is the difference between 181-360 and >36...,#-#,#-#,1503.0,-1503.00,,,True,0,sign_error,10
370,What is the increase / (decrease) in the Weigh...,#-#,#-#,0.5,0.00,million,million,False,0,selection_error,10
387,What is the increase / (decrease) in the prima...,#-#,#-#,-3270.0,881195.00,,,False,0,selection_error,10
399,What is the nominal difference for the number ...,#-#,#-#,54633874.0,NaN,,,False,0,runtime_error,10
441,What is the increase / (decrease) in the Opera...,#-#,#-#,393.0,NaN,million,,False,0,runtime_error,10
492,What is the change in total personnel expenses...,#-#,(#/#)*#,39224.0,20.81,,percent,False,0,calculation_error,10

In [153]:
errors.to_csv('res/errors_e38_23_cv1_4_1.csv')

In [14]:
errors = pd.read_csv('res/e38_34b.csv').query('exact_match == False')
X_features = prepare_matrix(errors)
try_hdbscan(X_features)

     0  1   2         3
31  15  2   2  0.082840
26  10  2   2  0.082840
30  15  1   2  0.088757
25  10  1   2  0.088757
28  10  4   2  0.177515
33  15  4   2  0.177515
16   5  2  11  0.177515
21   6  2   8  0.195266
0    2  1  39  0.201183
32  15  3   2  0.218935
27  10  3   2  0.218935
15   5  1  13  0.218935
29  10  5   2  0.254438
34  15  5   2  0.254438
5    3  1  27  0.266272
1    2  2  29  0.266272
20   6  1  10  0.278107
10   4  1  18  0.284024
6    3  2  22  0.284024
3    2  4  24  0.295858
2    2  3  31  0.307692
13   4  4  12  0.307692
4    2  5  23  0.331361
11   4  2  18  0.337278
7    3  3  18  0.366864
8    3  4  14  0.366864
17   5  3  10  0.372781
22   6  3   8  0.372781
18   5  4   8  0.378698
23   6  4   7  0.378698
12   4  3  14  0.402367
9    3  5  14  0.426036
14   4  5   9  0.461538
19   5  5   7  0.508876
24   6  5   7  0.508876

In [15]:
labels, thr = cluster_hdbscan(X_features, min_cluster_size=4, min_samples=1)
errors["labels"] = labels
errors["labels"].value_counts()

labels
-1     48
 1     12
 4     10
 13    10
 5     10
 16     9
 10     8
 7      7
 11     6
 2      6
 15     6
 14     5
 3      5
 12     5
 8      5
 0      5
 6      4
 9      4
 17     4
Name: count, dtype: int64

In [16]:
[(i["question"], i["calc_pattern"], i["code_calc_pattern"]) for idx, i in errors.iterrows() if i["labels"] == 16]

[('What is the 2019 average defined contribution schemes?', '(#+#)/#', '#/#'),
 ('What is the 2019 average defined benefit schemes?', '(#+#)/#', '#/#'),
 ('What is the 2018 average free cash flow?', '(#+#)/#', '#'),
 ('What is the average total current tax expense for 2017 and 2018? ',
  '(#+#)/#',
  '(#+#)/#'),
 ('What is the average total current tax expense for 2018 and 2019?',
  '(#+#)/#',
  '(#+#)/#'),
 ('What is the average total asset value for 2018 and 2019?',
  '(#+#)/#',
  '(#+#)/#'),
 ('What is the 2019 average total amount falling due within one year?',
  '(#+#)/#',
  '#'),
 ('What is the 2019 average total amount falling due after more than one year?',
  '(#+#)/#',
  '(#+#)/#'),
 ('What is the average unvested restricted stock?', '(#+#)/#', '#/#')]

In [17]:
errors = pd.read_csv('res/e38_35.csv').query('exact_match == False')
X_features = prepare_matrix(errors)
try_hdbscan(X_features)

     0  1   2         3
25  10  1   2  0.025157
26  10  2   2  0.094340
5    3  1  22  0.125786
10   4  1  17  0.132075
0    2  1  41  0.144654
30  15  1   2  0.150943
15   5  1  11  0.150943
27  10  3   2  0.157233
20   6  1  10  0.182390
2    2  3  27  0.226415
1    2  2  30  0.238994
22   6  3   9  0.251572
17   5  3   9  0.251572
6    3  2  22  0.283019
32  15  3   2  0.289308
3    2  4  21  0.314465
11   4  2  15  0.327044
4    2  5  24  0.339623
7    3  3  16  0.339623
12   4  3  13  0.352201
28  10  4   2  0.396226
21   6  2   9  0.396226
33  15  4   2  0.396226
16   5  2   9  0.396226
8    3  4  14  0.402516
31  15  2   2  0.433962
9    3  5  14  0.433962
13   4  4   8  0.477987
19   5  5   8  0.484277
14   4  5  11  0.490566
23   6  4   7  0.503145
18   5  4   7  0.503145
24   6  5   7  0.515723
29  10  5   2  0.547170
34  15  5   2  0.547170

In [18]:
labels, thr = cluster_hdbscan(X_features, min_cluster_size=4, min_samples=1)
errors["labels"] = labels
errors["labels"].value_counts()

labels
-1     21
 0     13
 3     13
 4     13
 11    12
 9     12
 10    10
 14     9
 15     8
 16     8
 7      7
 2      6
 1      6
 8      5
 5      4
 13     4
 12     4
 6      4
Name: count, dtype: int64

In [19]:
[(i["question"], i["calc_pattern"], i["code_calc_pattern"]) for idx, i in errors.iterrows() if i["labels"] == 7]

[('What is the change in the operating revenue under continuing operations from 2018 to 2019?',
  '#-#',
  ''),
 ('What was the change in percentage of sales represented by gross profit between 2018 and 2019?',
  '#-#',
  '((#-#)/#)*#'),
 ('What was the change in percentage of sales represented by provision for income taxes between 2018 and 2019?',
  '#-#',
  '((#-#)/#)*#'),
 ('What was the absolute percentage change in risk-free interest rate between 2018 and 2019?',
  '#-#',
  '((#-#)/#)*#'),
 ('What was the absolute percentage change in Expected volatility between 2019 and 2020?',
  '#-#',
  '((#-#)/#)*#'),
 ('What is the percentage increase / (decrease) in the loss from operations from 2018 to 2019?',
  '-#/-#-#',
  ''),
 ('How many percent did the weighted average hedged rate for the year change by from 2018 to 2019?',
  '#-#',
  '')]

In [45]:
errors = pd.read_csv('res/e38_36c.csv').query('exact_match == False')
X_features = prepare_matrix(errors)
try_hdbscan(X_features)

     0  1   2         3
30  15  1   3  0.125828
20   6  1   9  0.152318
0    2  1  41  0.172185
15   5  1  10  0.172185
31  15  2   3  0.192053
25  10  1   6  0.205298
5    3  1  23  0.238411
10   4  1  14  0.245033
26  10  2   5  0.245033
6    3  2  18  0.251656
1    2  2  23  0.258278
7    3  3  14  0.264901
4    2  5  20  0.278146
21   6  2   9  0.291391
2    2  3  23  0.291391
11   4  2  12  0.291391
3    2  4  22  0.304636
12   4  3  10  0.317881
28  10  4   5  0.331126
16   5  2  10  0.344371
27  10  3   5  0.350993
9    3  5  12  0.357616
14   4  5  12  0.357616
29  10  5   4  0.364238
17   5  3   8  0.370861
22   6  3   8  0.370861
19   5  5   8  0.403974
8    3  4  11  0.403974
32  15  3   3  0.417219
13   4  4  10  0.423841
24   6  5   7  0.437086
34  15  5   3  0.456954
23   6  4   8  0.476821
18   5  4   8  0.476821
33  15  4   3  0.490066

In [58]:
labels, thr = cluster_hdbscan(X_features, min_cluster_size=4, min_samples=1)
errors["labels"] = labels
errors["labels"].value_counts()

labels
-1     43
 17    14
 10    10
 12    10
 2      9
 7      6
 8      6
 0      5
 5      5
 11     5
 1      5
 3      5
 4      5
 15     5
 14     4
 6      4
 13     4
 9      4
 16     4
Name: count, dtype: int64

In [61]:
errors[["question","calc_pattern","code_calc_pattern","answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "error_code",  "labels"]].query('labels == 17')

,question,calc_pattern,code_calc_pattern,answer,pred,scale,pred_scale,sign_error,x100_flag,error_code,labels
34,What was the change in the preferred stock dis...,-#-#,#-#,-9.9,NaN,percent,,False,0,runtime_error,17
41,What is the change in the average total curren...,[(#+#)/#]-[(#+#)/#],#-#,56.0,NaN,million,,False,0,runtime_error,17
84,What is the increase/ (decrease) in total Fees...,#-#,#-#,-416429.0,NaN,,,False,0,runtime_error,17
185,What is the change in the Total Gross Margin b...,#%-#%,#-#,0.6,NaN,percent,,False,0,runtime_error,17
199,What is the nominal difference for basic earni...,#-#,#-#,73.6,NaN,,,False,0,runtime_error,17
253,How much more cloud and license revenues came ...,#-#,#-#,13182.0,NaN,million,,False,0,runtime_error,17
259,What is the change in Revenue of Software deli...,#-#,#-#,-1508.0,NaN,thousand,,False,0,runtime_error,17
344,What is the change in Net Sales from Fiscal Ye...,#-#,#,92.0,NaN,million,,False,0,runtime_error,17
345,What is the change in Income before Income Tax...,#-#,#-#,-20.2,NaN,million,,False,0,runtime_error,17
399,What is the nominal difference for the number ...,#-#,#-#,54633874.0,NaN,,,False,0,runtime_error,17
401,What is the nominal difference in contributed ...,#-#,#-#,227.0,NaN,million,,False,0,runtime_error,17
440,What is the increase / (decrease) in Acquisiti...,-#-#,#-#,-228.0,NaN,million,,False,0,runtime_error,17
441,What is the increase / (decrease) in the Opera...,#-#,#-#,393.0,NaN,million,,False,0,runtime_error,17
486,What was the increase / (decrease) in the FCC ...,#-#,#-#,15.6,NaN,million,,False,0,syntax_error,17

In [53]:
errors = pd.read_csv('res/e38_37d.csv').query('exact_match == False')
X_features = prepare_matrix(errors)
try_hdbscan(X_features)

     0  1   2         3
30  15  1   3  0.032680
34  15  5   2  0.124183
0    2  1  40  0.150327
5    3  1  26  0.176471
33  15  4   2  0.215686
1    2  2  27  0.228758
20   6  1   8  0.241830
6    3  2  20  0.241830
31  15  2   4  0.241830
25  10  1   6  0.241830
21   6  2   8  0.254902
26  10  2   5  0.267974
11   4  2  17  0.274510
16   5  2  11  0.281046
10   4  1  18  0.281046
4    2  5  21  0.287582
15   5  1  13  0.307190
8    3  4  13  0.320261
3    2  4  20  0.320261
22   6  3   8  0.339869
17   5  3   8  0.339869
27  10  3   4  0.346405
2    2  3  24  0.352941
9    3  5  11  0.359477
14   4  5   9  0.379085
19   5  5   9  0.379085
12   4  3  13  0.405229
7    3  3  15  0.411765
23   6  4   8  0.418301
13   4  4   8  0.418301
18   5  4   8  0.418301
28  10  4   3  0.431373
32  15  3   3  0.431373
24   6  5   7  0.444444
29  10  5   4  0.529412

In [54]:
labels, thr = cluster_hdbscan(X_features, min_cluster_size=4, min_samples=1)
errors["labels"] = labels
errors["labels"].value_counts()

labels
-1     43
 17    14
 10    10
 12    10
 2      9
 7      6
 8      6
 0      5
 5      5
 11     5
 1      5
 3      5
 4      5
 15     5
 14     4
 6      4
 13     4
 9      4
 16     4
Name: count, dtype: int64

In [60]:
errors[["question","calc_pattern","code_calc_pattern","answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "error_code",  "labels"]].query('labels == 17')

,question,calc_pattern,code_calc_pattern,answer,pred,scale,pred_scale,sign_error,x100_flag,error_code,labels
34,What was the change in the preferred stock dis...,-#-#,#-#,-9.9,NaN,percent,,False,0,runtime_error,17
41,What is the change in the average total curren...,[(#+#)/#]-[(#+#)/#],#-#,56.0,NaN,million,,False,0,runtime_error,17
84,What is the increase/ (decrease) in total Fees...,#-#,#-#,-416429.0,NaN,,,False,0,runtime_error,17
185,What is the change in the Total Gross Margin b...,#%-#%,#-#,0.6,NaN,percent,,False,0,runtime_error,17
199,What is the nominal difference for basic earni...,#-#,#-#,73.6,NaN,,,False,0,runtime_error,17
253,How much more cloud and license revenues came ...,#-#,#-#,13182.0,NaN,million,,False,0,runtime_error,17
259,What is the change in Revenue of Software deli...,#-#,#-#,-1508.0,NaN,thousand,,False,0,runtime_error,17
344,What is the change in Net Sales from Fiscal Ye...,#-#,#,92.0,NaN,million,,False,0,runtime_error,17
345,What is the change in Income before Income Tax...,#-#,#-#,-20.2,NaN,million,,False,0,runtime_error,17
399,What is the nominal difference for the number ...,#-#,#-#,54633874.0,NaN,,,False,0,runtime_error,17
401,What is the nominal difference in contributed ...,#-#,#-#,227.0,NaN,million,,False,0,runtime_error,17
440,What is the increase / (decrease) in Acquisiti...,-#-#,#-#,-228.0,NaN,million,,False,0,runtime_error,17
441,What is the increase / (decrease) in the Opera...,#-#,#-#,393.0,NaN,million,,False,0,runtime_error,17
486,What was the increase / (decrease) in the FCC ...,#-#,#-#,15.6,NaN,million,,False,0,syntax_error,17

In [102]:
errors = pd.read_csv('res/e38_38.csv').query('exact_match == False')

#X_features = prepare_matrix(errors, ["calc_pattern", "code_calc_pattern", "scale", "pred_scale"])

X_features = prepare_matrix(errors, ["calc_pattern", "code_calc_pattern", "scale", "pred_scale","x100_flag", "sign_error", 'error_code'])
try_hdbscan(X_features)

     0  1   2         3
30  15  1   5  0.090278
20   6  1  11  0.118056
15   5  1  11  0.118056
25  10  1   7  0.125000
28  10  4   3  0.138889
33  15  4   3  0.138889
5    3  1  22  0.152778
31  15  2   3  0.159722
26  10  2   3  0.159722
0    2  1  39  0.173611
10   4  1  18  0.173611
27  10  3   5  0.236111
1    2  2  28  0.250000
3    2  4  17  0.326389
11   4  2  12  0.326389
4    2  5  17  0.333333
17   5  3   9  0.347222
2    2  3  19  0.347222
6    3  2  18  0.347222
12   4  3  10  0.354167
7    3  3  14  0.361111
9    3  5  12  0.368056
32  15  3   3  0.381944
22   6  3   8  0.381944
18   5  4   7  0.388889
21   6  2   7  0.388889
23   6  4   7  0.388889
8    3  4  11  0.395833
14   4  5  10  0.409722
13   4  4   9  0.416667
16   5  2   8  0.437500
24   6  5   7  0.465278
19   5  5   7  0.465278
29  10  5   4  0.486111
34  15  5   2  0.548611

In [73]:
len(errors)

144

In [103]:
labels, thr = cluster_hdbscan(X_features, min_cluster_size=4, min_samples=1)
errors["labels"] = labels
errors["labels"].value_counts()

labels
-1     25
 5     18
 9     13
 4     11
 2      9
 13     8
 1      6
 3      6
 14     6
 7      5
 10     5
 6      4
 0      4
 16     4
 17     4
 8      4
 11     4
 15     4
 12     4
Name: count, dtype: int64

In [106]:
errors[["question","calc_pattern","code_calc_pattern","answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "error_code",  "labels"]].query('labels == 4')

,question,calc_pattern,code_calc_pattern,answer,pred,scale,pred_scale,sign_error,x100_flag,error_code,labels
11,"What is the proportion of IMFT’s property, pla...",#/#,#,0.87,0.87,,percent,False,0,scale_error,4
43,What was the employee termination costs as a p...,#/#,#/#,0.95,0.04,,percent,False,0,selection_error,4
61,What is the proportion of granted shares betwe...,#/#,#/#,0.11,0.10,,percent,False,0,selection_error,4
171,What is the average INR-GBP exchange rate in F...,#/#,#/#,0.01,0.88,,percent,False,0,calculation_error,4
173,What is the current ratio in 2019?,#/#,,0.78,0.78,,thousand,False,0,scale_error,4
224,What was the domestic-state tax credit carryfo...,#/#,#/#,0.08,0.08,percent,thousand,False,0,scale_error,4
331,What proportion of Total FairValue is made up ...,#/#,#/#,1.00,1.00,,percent,False,0,scale_error,4
411,What is the proportion of land and leasehold i...,(#+#)/#,#/#,0.18,0.18,,thousand,False,0,scale_error,4
412,"What is the ratio of the gross cost of land, p...",#/#,#/#,0.97,0.97,,thousand,False,0,scale_error,4
436,What is the ratio of inventory reserves to acc...,#/#,#/#,2.65,2.65,,thousand,False,0,scale_error,4
484,What is the proportion of long-term debt payme...,(#+#)/#,#/#,0.48,0.48,,million,False,0,scale_error,4