In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt
from pathlib import Path
import textwrap
import cga_utils
import math
from typing import Iterable, List, Optional, Tuple
import hdbscan
from sklearn.feature_extraction import DictVectorizer
import cluster_features

## v18

In [125]:
errors = pd.read_csv('res/e38_18.csv').query('exact_match == False')
X_features = prepare_matrix(errors, ["calc_pattern", "code_calc_pattern", "scale", "pred_scale"])
try_hdbscan(X_features)

     0  1   2         3
30  15  1   2  0.165829
32  15  3   4  0.185930
27  10  3   4  0.185930
3    2  4  30  0.190955
0    2  1  43  0.206030
25  10  1   3  0.206030
11   4  2  16  0.226131
16   5  2  16  0.226131
4    2  5  25  0.236181
28  10  4   2  0.246231
33  15  4   2  0.246231
1    2  2  32  0.256281
21   6  2  14  0.276382
2    2  3  31  0.286432
6    3  2  24  0.296482
15   5  1  13  0.296482
9    3  5  18  0.296482
26  10  2   6  0.316583
17   5  3  10  0.316583
10   4  1  18  0.316583
29  10  5   3  0.336683
34  15  5   3  0.336683
14   4  5  15  0.341709
22   6  3   8  0.341709
13   4  4  14  0.341709
8    3  4  14  0.341709
20   6  1  11  0.346734
19   5  5  11  0.356784
24   6  5  11  0.356784
5    3  1  22  0.356784
18   5  4  11  0.371859
23   6  4   9  0.396985
7    3  3  15  0.412060
12   4  3  14  0.427136
31  15  2   3  0.427136

In [126]:
labels, thr = cluster_hdbscan(X_features, min_cluster_size=4, min_samples=2)

In [127]:
(labels == -1).mean()

0.22613065326633167

In [128]:
labels

array([ 4, 15, 15, -1,  5, 15, 15, -1, -1, 10,  1,  1,  9,  4, 11,  4, -1,
       15, 15,  3,  1, -1, -1, -1, 12, -1, -1, -1, 12, 12,  8, 12, -1, -1,
       13, 13, 13, 14,  5, -1, 13,  5, 14, 10,  0, 10, 13,  6, -1,  9, 12,
       -1,  5,  7, -1,  7, -1, 15, 15,  5, -1,  5, 10, -1, 13, -1, -1, -1,
       15,  9,  9,  6, 14,  8, -1, -1, -1,  2,  6,  6,  6, 11,  4,  1, 14,
        1,  1, 14, 13, 15, -1, -1, -1,  2,  2, 12, -1,  3,  4,  2, -1,  7,
        7,  8,  8, 12, -1,  4, 12, 12,  1,  1, -1, -1,  1,  8, 11, 12, 12,
       -1, 12,  1, -1, -1, 12, 11, 11, 11,  4, 13, 13,  4,  7, 12, 14,  3,
       12,  9,  3,  3,  9, 12, -1, 10,  0,  8, -1,  6, -1, -1,  0, 12,  4,
       10, 15, 15,  5,  6, -1,  8,  6,  8, 15, 10, 12, 12, 13, 15, 15, 12,
       11,  5,  1,  4,  6,  0,  0, -1, 13, -1, 15, 10, 10,  0, -1,  3,  8,
        4, 10,  2, 12,  5, -1,  1, 12, 15, 14, 14, 14])

In [133]:
errors["cluster"] = labels

In [136]:
errors["cluster"].value_counts()

cluster
-1     45
 12    22
 15    17
 1     12
 4     11
 13    11
 10    10
 5      9
 6      9
 8      9
 14     9
 11     7
 0      6
 3      6
 9      6
 7      5
 2      5
Name: count, dtype: int64

In [142]:
#errors[["question","calc_pattern","code_calc_pattern","answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "error_code",  "cluster"]].query('cluster == 12')
errors[["question","calc_pattern","code_calc_pattern","answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "error_code",  "cluster"]].query('cluster == cluster[cluster != -1].value_counts().idxmax()')

,question,calc_pattern,code_calc_pattern,answer,pred,scale,pred_scale,sign_error,x100_flag,error_code,cluster
54,What was the percentage change in Total Other ...,(#-#)/#,((#-#)/#)*#,15.85,15.85,percent,,False,0,scale_error,12
67,What was the percentage change in Adjusted EBI...,(#-#)/#,((#-#)/#)*#,16.36,16.36,percent,,False,0,scale_error,12
68,What was the percentage change in the Total ne...,(#-#)/#,((#-#)/#)*#,-22.26,-22.26,percent,,False,0,scale_error,12
71,What is the percentage increase in the number ...,(#-#)/#,((#-#)/#)*#,58.71,58.71,percent,,False,0,scale_error,12
140,What was the percentage change in net deferred...,(#-#)/#,((#-#)/#)*#,-79.67,NaN,percent,,False,0,runtime_error,12
252,What was the percentage change in the average ...,(#-#)/#,((#-#)/#)*#,-0.57,-0.57,percent,,False,0,scale_error,12
273,What is the percentage change in the total fai...,(#-#)/#,((#-#)/#)*#,0.53,0.53,percent,,False,0,scale_error,12
284,What is the percentage increase in cash provid...,(#-#)/#,((#-#)/#)*#,-21.92,-21.92,percent,,False,0,scale_error,12
285,What is the percentage change in the total oth...,(#-#)/#,((#-#)/#)*#,385.45,385.45,percent,,False,0,scale_error,12
294,What is the percentage change in the research ...,(#-#)/#,((#-#)/#)*#,3.85,3.85,percent,,False,0,scale_error,12
296,What is the percentage change in the finance c...,(#-#)/#,((#-#)/#)*#,222.58,222.58,percent,,False,0,scale_error,12
298,What is the percentage change in cash provided...,(#-#)/#,((#-#)/#)*#,59.99,59.99,percent,,False,0,scale_error,12
303,What is the percentage change of net operating...,(#-#)/#,((#-#)/#)*#,84.53,84.53,percent,,False,0,scale_error,12
326,What was the percentage change in the Share ba...,(#-#)/#,((#-#)/#)*#,6.05,NaN,percent,,False,0,runtime_error,12
336,What was the percentage change in the amount O...,(#-#)/#,((#-#)/#)*#,15.72,15.72,percent,,False,0,scale_error,12
343,What was the percentage change in the number o...,(#-#)/#,((#-#)/#)*#,10.34,10.34,percent,,False,0,scale_error,12
367,What was the percentage change in the amount O...,(#-#)/#,((#-#)/#)*#,-53.55,-53.55,percent,,False,0,scale_error,12
402,What is the percentage change in net income be...,(#-#)/#,((#-#)/#)*#,-13.25,-13.25,percent,,False,0,scale_error,12
409,What is the percentage change in net cash prov...,(#-#)/#,((#-#)/#)*#,33.69,33.69,percent,,False,0,scale_error,12
413,What is the percentage increase in Swiss incom...,(#-#)/#,(#/#)*#,10.15,10.15,percent,,False,0,scale_error,12
475,What is the percentage change of revenue from ...,(#-#)/#,((#-#)/#)*#,23.23,23.23,percent,,False,0,scale_error,12
480,What is the percentage change in the total bal...,(#-#)/#,((#-#)/#)*#,49.92,49.92,percent,,False,0,scale_error,12

In [139]:
errors.to_csv('res/errors_e38_18_cv1_4_2.csv')

## v23

In [3]:
errors = pd.read_csv('res/e38_23.csv').query('exact_match == False')
X_features = cluster_features.prepare_matrix(errors, ["calc_pattern", "code_calc_pattern", "scale", "pred_scale"])
cluster_features.try_hdbscan(X_features)

     0  1   2         3
34  15  5   2  0.000000
29  10  5   2  0.000000
28  10  4   2  0.113636
27  10  3   2  0.113636
25  10  1   2  0.142045
31  15  2   2  0.198864
26  10  2   2  0.198864
0    2  1  39  0.204545
33  15  4   2  0.210227
5    3  1  28  0.250000
1    2  2  33  0.250000
10   4  1  21  0.289773
15   5  1  13  0.306818
3    2  4  21  0.306818
4    2  5  21  0.312500
6    3  2  26  0.318182
9    3  5  15  0.335227
20   6  1  12  0.335227
11   4  2  20  0.340909
23   6  4   8  0.340909
2    2  3  26  0.352273
30  15  1   2  0.363636
18   5  4   9  0.363636
13   4  4   9  0.363636
14   4  5  10  0.380682
8    3  4  11  0.392045
32  15  3   2  0.414773
19   5  5   7  0.420455
16   5  2  11  0.420455
7    3  3  18  0.426136
21   6  2   9  0.437500
24   6  5   6  0.448864
17   5  3  11  0.454545
12   4  3  14  0.471591
22   6  3  10  0.482955

In [4]:
labels, pers, probs = cluster_features.cluster_hdbscan(X_features, min_cluster_size=4, min_samples=1)
errors["cluster"] = labels
errors["cluster"].value_counts()

pers:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

cluster
-1     51
 12    10
 15     9
 14     8
 0      8
 5      7
 19     7
 13     7
 10     7
 8      6
 3      6
 7      6
 4      5
 2      5
 6      5
 1      5
 17     4
 16     4
 9      4
 11     4
 20     4
 18     4
Name: count, dtype: int64

In [6]:
errors[["question","calc_pattern","code_calc_pattern","answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "error_code",  "cluster"]].query('cluster == 15')
#errors[["question","calc_pattern","code_calc_pattern","answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "error_code",  "cluster"]].query('cluster == cluster[cluster != -1].value_counts().idxmax()')

,question,calc_pattern,code_calc_pattern,answer,pred,scale,pred_scale,sign_error,x100_flag,error_code,cluster
39,What is the average total current tax expense ...,(#+#)/#,(#+#)/#,984.0,NaN,million,,False,0,runtime_error,15
40,What is the average total current tax expense ...,(#+#)/#,(#+#)/#,1040.0,NaN,million,,False,0,runtime_error,15
178,What is the total equity of the acquisation as...,#-#,#-#,445.7,445.7,million,,False,0,scale_error,15
253,How much more cloud and license revenues came ...,#-#,#-#,13182.0,NaN,million,,False,0,runtime_error,15
345,What is the change in Income before Income Tax...,#-#,#-#,-20.2,NaN,million,,False,0,runtime_error,15
357,What is the average depreciation and amortizat...,(#+#)/#,(#+#)/#,0.1,0.1,million,,False,0,scale_error,15
400,What is the average contributed equity at end ...,(#+#)/#,,5941.5,NaN,million,,False,0,runtime_error,15
401,What is the nominal difference in contributed ...,#-#,,227.0,NaN,million,,False,0,runtime_error,15
441,What is the increase / (decrease) in the Opera...,#-#,#-#,393.0,NaN,million,,False,0,runtime_error,15

In [153]:
errors.to_csv('res/errors_e38_23_cv1_4_1.csv')

In [14]:
errors = pd.read_csv('res/e38_34b.csv').query('exact_match == False')
X_features = prepare_matrix(errors)
try_hdbscan(X_features)

     0  1   2         3
31  15  2   2  0.082840
26  10  2   2  0.082840
30  15  1   2  0.088757
25  10  1   2  0.088757
28  10  4   2  0.177515
33  15  4   2  0.177515
16   5  2  11  0.177515
21   6  2   8  0.195266
0    2  1  39  0.201183
32  15  3   2  0.218935
27  10  3   2  0.218935
15   5  1  13  0.218935
29  10  5   2  0.254438
34  15  5   2  0.254438
5    3  1  27  0.266272
1    2  2  29  0.266272
20   6  1  10  0.278107
10   4  1  18  0.284024
6    3  2  22  0.284024
3    2  4  24  0.295858
2    2  3  31  0.307692
13   4  4  12  0.307692
4    2  5  23  0.331361
11   4  2  18  0.337278
7    3  3  18  0.366864
8    3  4  14  0.366864
17   5  3  10  0.372781
22   6  3   8  0.372781
18   5  4   8  0.378698
23   6  4   7  0.378698
12   4  3  14  0.402367
9    3  5  14  0.426036
14   4  5   9  0.461538
19   5  5   7  0.508876
24   6  5   7  0.508876

In [15]:
labels, thr = cluster_hdbscan(X_features, min_cluster_size=4, min_samples=1)
errors["labels"] = labels
errors["labels"].value_counts()

labels
-1     48
 1     12
 4     10
 13    10
 5     10
 16     9
 10     8
 7      7
 11     6
 2      6
 15     6
 14     5
 3      5
 12     5
 8      5
 0      5
 6      4
 9      4
 17     4
Name: count, dtype: int64

In [16]:
[(i["question"], i["calc_pattern"], i["code_calc_pattern"]) for idx, i in errors.iterrows() if i["labels"] == 16]

[('What is the 2019 average defined contribution schemes?', '(#+#)/#', '#/#'),
 ('What is the 2019 average defined benefit schemes?', '(#+#)/#', '#/#'),
 ('What is the 2018 average free cash flow?', '(#+#)/#', '#'),
 ('What is the average total current tax expense for 2017 and 2018? ',
  '(#+#)/#',
  '(#+#)/#'),
 ('What is the average total current tax expense for 2018 and 2019?',
  '(#+#)/#',
  '(#+#)/#'),
 ('What is the average total asset value for 2018 and 2019?',
  '(#+#)/#',
  '(#+#)/#'),
 ('What is the 2019 average total amount falling due within one year?',
  '(#+#)/#',
  '#'),
 ('What is the 2019 average total amount falling due after more than one year?',
  '(#+#)/#',
  '(#+#)/#'),
 ('What is the average unvested restricted stock?', '(#+#)/#', '#/#')]

In [17]:
errors = pd.read_csv('res/e38_35.csv').query('exact_match == False')
X_features = prepare_matrix(errors)
try_hdbscan(X_features)

     0  1   2         3
25  10  1   2  0.025157
26  10  2   2  0.094340
5    3  1  22  0.125786
10   4  1  17  0.132075
0    2  1  41  0.144654
30  15  1   2  0.150943
15   5  1  11  0.150943
27  10  3   2  0.157233
20   6  1  10  0.182390
2    2  3  27  0.226415
1    2  2  30  0.238994
22   6  3   9  0.251572
17   5  3   9  0.251572
6    3  2  22  0.283019
32  15  3   2  0.289308
3    2  4  21  0.314465
11   4  2  15  0.327044
4    2  5  24  0.339623
7    3  3  16  0.339623
12   4  3  13  0.352201
28  10  4   2  0.396226
21   6  2   9  0.396226
33  15  4   2  0.396226
16   5  2   9  0.396226
8    3  4  14  0.402516
31  15  2   2  0.433962
9    3  5  14  0.433962
13   4  4   8  0.477987
19   5  5   8  0.484277
14   4  5  11  0.490566
23   6  4   7  0.503145
18   5  4   7  0.503145
24   6  5   7  0.515723
29  10  5   2  0.547170
34  15  5   2  0.547170

In [18]:
labels, thr = cluster_hdbscan(X_features, min_cluster_size=4, min_samples=1)
errors["labels"] = labels
errors["labels"].value_counts()

labels
-1     21
 0     13
 3     13
 4     13
 11    12
 9     12
 10    10
 14     9
 15     8
 16     8
 7      7
 2      6
 1      6
 8      5
 5      4
 13     4
 12     4
 6      4
Name: count, dtype: int64

In [19]:
[(i["question"], i["calc_pattern"], i["code_calc_pattern"]) for idx, i in errors.iterrows() if i["labels"] == 7]

[('What is the change in the operating revenue under continuing operations from 2018 to 2019?',
  '#-#',
  ''),
 ('What was the change in percentage of sales represented by gross profit between 2018 and 2019?',
  '#-#',
  '((#-#)/#)*#'),
 ('What was the change in percentage of sales represented by provision for income taxes between 2018 and 2019?',
  '#-#',
  '((#-#)/#)*#'),
 ('What was the absolute percentage change in risk-free interest rate between 2018 and 2019?',
  '#-#',
  '((#-#)/#)*#'),
 ('What was the absolute percentage change in Expected volatility between 2019 and 2020?',
  '#-#',
  '((#-#)/#)*#'),
 ('What is the percentage increase / (decrease) in the loss from operations from 2018 to 2019?',
  '-#/-#-#',
  ''),
 ('How many percent did the weighted average hedged rate for the year change by from 2018 to 2019?',
  '#-#',
  '')]

In [45]:
errors = pd.read_csv('res/e38_36c.csv').query('exact_match == False')
X_features = prepare_matrix(errors)
try_hdbscan(X_features)

     0  1   2         3
30  15  1   3  0.125828
20   6  1   9  0.152318
0    2  1  41  0.172185
15   5  1  10  0.172185
31  15  2   3  0.192053
25  10  1   6  0.205298
5    3  1  23  0.238411
10   4  1  14  0.245033
26  10  2   5  0.245033
6    3  2  18  0.251656
1    2  2  23  0.258278
7    3  3  14  0.264901
4    2  5  20  0.278146
21   6  2   9  0.291391
2    2  3  23  0.291391
11   4  2  12  0.291391
3    2  4  22  0.304636
12   4  3  10  0.317881
28  10  4   5  0.331126
16   5  2  10  0.344371
27  10  3   5  0.350993
9    3  5  12  0.357616
14   4  5  12  0.357616
29  10  5   4  0.364238
17   5  3   8  0.370861
22   6  3   8  0.370861
19   5  5   8  0.403974
8    3  4  11  0.403974
32  15  3   3  0.417219
13   4  4  10  0.423841
24   6  5   7  0.437086
34  15  5   3  0.456954
23   6  4   8  0.476821
18   5  4   8  0.476821
33  15  4   3  0.490066

In [58]:
labels, thr = cluster_hdbscan(X_features, min_cluster_size=4, min_samples=1)
errors["labels"] = labels
errors["labels"].value_counts()

labels
-1     43
 17    14
 10    10
 12    10
 2      9
 7      6
 8      6
 0      5
 5      5
 11     5
 1      5
 3      5
 4      5
 15     5
 14     4
 6      4
 13     4
 9      4
 16     4
Name: count, dtype: int64

In [61]:
errors[["question","calc_pattern","code_calc_pattern","answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "error_code",  "labels"]].query('labels == 17')

,question,calc_pattern,code_calc_pattern,answer,pred,scale,pred_scale,sign_error,x100_flag,error_code,labels
34,What was the change in the preferred stock dis...,-#-#,#-#,-9.9,NaN,percent,,False,0,runtime_error,17
41,What is the change in the average total curren...,[(#+#)/#]-[(#+#)/#],#-#,56.0,NaN,million,,False,0,runtime_error,17
84,What is the increase/ (decrease) in total Fees...,#-#,#-#,-416429.0,NaN,,,False,0,runtime_error,17
185,What is the change in the Total Gross Margin b...,#%-#%,#-#,0.6,NaN,percent,,False,0,runtime_error,17
199,What is the nominal difference for basic earni...,#-#,#-#,73.6,NaN,,,False,0,runtime_error,17
253,How much more cloud and license revenues came ...,#-#,#-#,13182.0,NaN,million,,False,0,runtime_error,17
259,What is the change in Revenue of Software deli...,#-#,#-#,-1508.0,NaN,thousand,,False,0,runtime_error,17
344,What is the change in Net Sales from Fiscal Ye...,#-#,#,92.0,NaN,million,,False,0,runtime_error,17
345,What is the change in Income before Income Tax...,#-#,#-#,-20.2,NaN,million,,False,0,runtime_error,17
399,What is the nominal difference for the number ...,#-#,#-#,54633874.0,NaN,,,False,0,runtime_error,17
401,What is the nominal difference in contributed ...,#-#,#-#,227.0,NaN,million,,False,0,runtime_error,17
440,What is the increase / (decrease) in Acquisiti...,-#-#,#-#,-228.0,NaN,million,,False,0,runtime_error,17
441,What is the increase / (decrease) in the Opera...,#-#,#-#,393.0,NaN,million,,False,0,runtime_error,17
486,What was the increase / (decrease) in the FCC ...,#-#,#-#,15.6,NaN,million,,False,0,syntax_error,17

In [53]:
errors = pd.read_csv('res/e38_37d.csv').query('exact_match == False')
X_features = prepare_matrix(errors)
try_hdbscan(X_features)

     0  1   2         3
30  15  1   3  0.032680
34  15  5   2  0.124183
0    2  1  40  0.150327
5    3  1  26  0.176471
33  15  4   2  0.215686
1    2  2  27  0.228758
20   6  1   8  0.241830
6    3  2  20  0.241830
31  15  2   4  0.241830
25  10  1   6  0.241830
21   6  2   8  0.254902
26  10  2   5  0.267974
11   4  2  17  0.274510
16   5  2  11  0.281046
10   4  1  18  0.281046
4    2  5  21  0.287582
15   5  1  13  0.307190
8    3  4  13  0.320261
3    2  4  20  0.320261
22   6  3   8  0.339869
17   5  3   8  0.339869
27  10  3   4  0.346405
2    2  3  24  0.352941
9    3  5  11  0.359477
14   4  5   9  0.379085
19   5  5   9  0.379085
12   4  3  13  0.405229
7    3  3  15  0.411765
23   6  4   8  0.418301
13   4  4   8  0.418301
18   5  4   8  0.418301
28  10  4   3  0.431373
32  15  3   3  0.431373
24   6  5   7  0.444444
29  10  5   4  0.529412

In [54]:
labels, thr = cluster_hdbscan(X_features, min_cluster_size=4, min_samples=1)
errors["labels"] = labels
errors["labels"].value_counts()

labels
-1     43
 17    14
 10    10
 12    10
 2      9
 7      6
 8      6
 0      5
 5      5
 11     5
 1      5
 3      5
 4      5
 15     5
 14     4
 6      4
 13     4
 9      4
 16     4
Name: count, dtype: int64

In [60]:
errors[["question","calc_pattern","code_calc_pattern","answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "error_code",  "labels"]].query('labels == 17')

,question,calc_pattern,code_calc_pattern,answer,pred,scale,pred_scale,sign_error,x100_flag,error_code,labels
34,What was the change in the preferred stock dis...,-#-#,#-#,-9.9,NaN,percent,,False,0,runtime_error,17
41,What is the change in the average total curren...,[(#+#)/#]-[(#+#)/#],#-#,56.0,NaN,million,,False,0,runtime_error,17
84,What is the increase/ (decrease) in total Fees...,#-#,#-#,-416429.0,NaN,,,False,0,runtime_error,17
185,What is the change in the Total Gross Margin b...,#%-#%,#-#,0.6,NaN,percent,,False,0,runtime_error,17
199,What is the nominal difference for basic earni...,#-#,#-#,73.6,NaN,,,False,0,runtime_error,17
253,How much more cloud and license revenues came ...,#-#,#-#,13182.0,NaN,million,,False,0,runtime_error,17
259,What is the change in Revenue of Software deli...,#-#,#-#,-1508.0,NaN,thousand,,False,0,runtime_error,17
344,What is the change in Net Sales from Fiscal Ye...,#-#,#,92.0,NaN,million,,False,0,runtime_error,17
345,What is the change in Income before Income Tax...,#-#,#-#,-20.2,NaN,million,,False,0,runtime_error,17
399,What is the nominal difference for the number ...,#-#,#-#,54633874.0,NaN,,,False,0,runtime_error,17
401,What is the nominal difference in contributed ...,#-#,#-#,227.0,NaN,million,,False,0,runtime_error,17
440,What is the increase / (decrease) in Acquisiti...,-#-#,#-#,-228.0,NaN,million,,False,0,runtime_error,17
441,What is the increase / (decrease) in the Opera...,#-#,#-#,393.0,NaN,million,,False,0,runtime_error,17
486,What was the increase / (decrease) in the FCC ...,#-#,#-#,15.6,NaN,million,,False,0,syntax_error,17

In [102]:
errors = pd.read_csv('res/e38_38.csv').query('exact_match == False')

#X_features = prepare_matrix(errors, ["calc_pattern", "code_calc_pattern", "scale", "pred_scale"])

X_features = prepare_matrix(errors, ["calc_pattern", "code_calc_pattern", "scale", "pred_scale","x100_flag", "sign_error", 'error_code'])
try_hdbscan(X_features)

     0  1   2         3
30  15  1   5  0.090278
20   6  1  11  0.118056
15   5  1  11  0.118056
25  10  1   7  0.125000
28  10  4   3  0.138889
33  15  4   3  0.138889
5    3  1  22  0.152778
31  15  2   3  0.159722
26  10  2   3  0.159722
0    2  1  39  0.173611
10   4  1  18  0.173611
27  10  3   5  0.236111
1    2  2  28  0.250000
3    2  4  17  0.326389
11   4  2  12  0.326389
4    2  5  17  0.333333
17   5  3   9  0.347222
2    2  3  19  0.347222
6    3  2  18  0.347222
12   4  3  10  0.354167
7    3  3  14  0.361111
9    3  5  12  0.368056
32  15  3   3  0.381944
22   6  3   8  0.381944
18   5  4   7  0.388889
21   6  2   7  0.388889
23   6  4   7  0.388889
8    3  4  11  0.395833
14   4  5  10  0.409722
13   4  4   9  0.416667
16   5  2   8  0.437500
24   6  5   7  0.465278
19   5  5   7  0.465278
29  10  5   4  0.486111
34  15  5   2  0.548611

In [73]:
len(errors)

144

In [103]:
labels, thr = cluster_hdbscan(X_features, min_cluster_size=4, min_samples=1)
errors["labels"] = labels
errors["labels"].value_counts()

labels
-1     25
 5     18
 9     13
 4     11
 2      9
 13     8
 1      6
 3      6
 14     6
 7      5
 10     5
 6      4
 0      4
 16     4
 17     4
 8      4
 11     4
 15     4
 12     4
Name: count, dtype: int64

In [106]:
errors[["question","calc_pattern","code_calc_pattern","answer","pred" ,'scale', 'pred_scale', 'sign_error', "x100_flag", "error_code",  "labels"]].query('labels == 4')

,question,calc_pattern,code_calc_pattern,answer,pred,scale,pred_scale,sign_error,x100_flag,error_code,labels
11,"What is the proportion of IMFT’s property, pla...",#/#,#,0.87,0.87,,percent,False,0,scale_error,4
43,What was the employee termination costs as a p...,#/#,#/#,0.95,0.04,,percent,False,0,selection_error,4
61,What is the proportion of granted shares betwe...,#/#,#/#,0.11,0.10,,percent,False,0,selection_error,4
171,What is the average INR-GBP exchange rate in F...,#/#,#/#,0.01,0.88,,percent,False,0,calculation_error,4
173,What is the current ratio in 2019?,#/#,,0.78,0.78,,thousand,False,0,scale_error,4
224,What was the domestic-state tax credit carryfo...,#/#,#/#,0.08,0.08,percent,thousand,False,0,scale_error,4
331,What proportion of Total FairValue is made up ...,#/#,#/#,1.00,1.00,,percent,False,0,scale_error,4
411,What is the proportion of land and leasehold i...,(#+#)/#,#/#,0.18,0.18,,thousand,False,0,scale_error,4
412,"What is the ratio of the gross cost of land, p...",#/#,#/#,0.97,0.97,,thousand,False,0,scale_error,4
436,What is the ratio of inventory reserves to acc...,#/#,#/#,2.65,2.65,,thousand,False,0,scale_error,4
484,What is the proportion of long-term debt payme...,(#+#)/#,#/#,0.48,0.48,,million,False,0,scale_error,4